apiVersion: v2
name: angzarr-domain
description: Deploy a single angzarr domain component (aggregate, saga, or projector)
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/benjaminabbitt/angzarr
sources:
  - https://github.com/benjaminabbitt/angzarr
keywords:
  - cqrs
  - event-sourcing
  - domain
  - aggregate
  - saga
  - projector
maintainers:
  - name: Benjamin Abbitt
