// @generated
// This file is @generated by prost-build.
// =============================================================================
// Order Domain - manages customer orders and payment
// =============================================================================

/// Commands
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateOrder {
    #[prost(string, tag = "1")]
    pub customer_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<LineItem>,
    /// customer aggregate root UUID for saga routing
    #[prost(bytes = "vec", tag = "3")]
    pub customer_root: ::prost::alloc::vec::Vec<u8>,
    /// cart aggregate root UUID for inventory reservation linking
    #[prost(bytes = "vec", tag = "4")]
    pub cart_root: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApplyLoyaltyDiscount {
    /// loyalty points to use
    #[prost(int32, tag = "1")]
    pub points: i32,
    /// value of discount in cents
    #[prost(int32, tag = "2")]
    pub discount_cents: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitPayment {
    /// "card", "cash", etc.
    #[prost(string, tag = "1")]
    pub payment_method: ::prost::alloc::string::String,
    /// payment amount (must match total after discount)
    #[prost(int32, tag = "2")]
    pub amount_cents: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfirmPayment {
    /// external payment reference
    #[prost(string, tag = "1")]
    pub payment_reference: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelOrder {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
/// Events
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderCreated {
    #[prost(string, tag = "1")]
    pub customer_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<LineItem>,
    #[prost(int32, tag = "3")]
    pub subtotal_cents: i32,
    #[prost(message, optional, tag = "4")]
    pub created_at: ::core::option::Option<super::google::protobuf::Timestamp>,
    /// customer aggregate root UUID
    #[prost(bytes = "vec", tag = "5")]
    pub customer_root: ::prost::alloc::vec::Vec<u8>,
    /// cart aggregate root UUID for inventory reservation linking
    #[prost(bytes = "vec", tag = "6")]
    pub cart_root: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoyaltyDiscountApplied {
    #[prost(int32, tag = "1")]
    pub points_used: i32,
    #[prost(int32, tag = "2")]
    pub discount_cents: i32,
    #[prost(message, optional, tag = "3")]
    pub applied_at: ::core::option::Option<super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentSubmitted {
    #[prost(string, tag = "1")]
    pub payment_method: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub amount_cents: i32,
    #[prost(message, optional, tag = "3")]
    pub submitted_at: ::core::option::Option<super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderCompleted {
    #[prost(int32, tag = "1")]
    pub final_total_cents: i32,
    #[prost(string, tag = "2")]
    pub payment_method: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub payment_reference: ::prost::alloc::string::String,
    /// Points to award customer (1 point per $1)
    #[prost(int32, tag = "4")]
    pub loyalty_points_earned: i32,
    #[prost(message, optional, tag = "5")]
    pub completed_at: ::core::option::Option<super::google::protobuf::Timestamp>,
    /// customer aggregate root UUID for saga routing
    #[prost(bytes = "vec", tag = "6")]
    pub customer_root: ::prost::alloc::vec::Vec<u8>,
    /// cart aggregate root UUID for inventory reservation commit
    #[prost(bytes = "vec", tag = "7")]
    pub cart_root: ::prost::alloc::vec::Vec<u8>,
    /// order items for inventory saga routing
    #[prost(message, repeated, tag = "8")]
    pub items: ::prost::alloc::vec::Vec<LineItem>,
    /// External service enrichment - demonstrates calling ANY external REST/gRPC service
    /// (pricing, tax, address validation, payment gateways, analytics/ML, etc.)
    /// Values: "approved", "review_required", "declined" - from fraud service
    #[prost(string, tag = "9")]
    pub fraud_check_result: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderCancelled {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub cancelled_at: ::core::option::Option<super::google::protobuf::Timestamp>,
    #[prost(int32, tag = "3")]
    pub loyalty_points_used: i32,
    /// customer aggregate root UUID for saga routing
    #[prost(bytes = "vec", tag = "4")]
    pub customer_root: ::prost::alloc::vec::Vec<u8>,
    /// order items for inventory saga routing
    #[prost(message, repeated, tag = "5")]
    pub items: ::prost::alloc::vec::Vec<LineItem>,
    /// cart aggregate root UUID for inventory reservation release
    #[prost(bytes = "vec", tag = "6")]
    pub cart_root: ::prost::alloc::vec::Vec<u8>,
}
/// Shared types
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LineItem {
    #[prost(string, tag = "1")]
    pub product_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub quantity: i32,
    #[prost(int32, tag = "4")]
    pub unit_price_cents: i32,
    /// product/inventory aggregate root UUID for saga routing
    #[prost(bytes = "vec", tag = "5")]
    pub product_root: ::prost::alloc::vec::Vec<u8>,
}
/// State (for snapshots)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderState {
    #[prost(string, tag = "1")]
    pub customer_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<LineItem>,
    #[prost(int32, tag = "3")]
    pub subtotal_cents: i32,
    #[prost(int32, tag = "4")]
    pub discount_cents: i32,
    #[prost(int32, tag = "5")]
    pub loyalty_points_used: i32,
    #[prost(string, tag = "6")]
    pub payment_method: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub payment_reference: ::prost::alloc::string::String,
    /// "pending", "payment_submitted", "completed", "cancelled"
    #[prost(string, tag = "8")]
    pub status: ::prost::alloc::string::String,
    /// customer aggregate root UUID
    #[prost(bytes = "vec", tag = "9")]
    pub customer_root: ::prost::alloc::vec::Vec<u8>,
    /// cart aggregate root UUID for inventory reservation linking
    #[prost(bytes = "vec", tag = "10")]
    pub cart_root: ::prost::alloc::vec::Vec<u8>,
}
// =============================================================================
// Fulfillment Domain - manages shipment lifecycle
// =============================================================================

/// Commands
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateShipment {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    /// order items for inventory commit on ship
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<LineItem>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkPicked {
    #[prost(string, tag = "1")]
    pub picker_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkPacked {
    #[prost(string, tag = "1")]
    pub packer_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ship {
    #[prost(string, tag = "1")]
    pub carrier: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tracking_number: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordDelivery {
    #[prost(string, tag = "1")]
    pub signature: ::prost::alloc::string::String,
}
/// Events
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShipmentCreated {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub created_at: ::core::option::Option<super::google::protobuf::Timestamp>,
    /// order items for inventory commit on ship
    #[prost(message, repeated, tag = "4")]
    pub items: ::prost::alloc::vec::Vec<LineItem>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ItemsPicked {
    #[prost(string, tag = "1")]
    pub picker_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub picked_at: ::core::option::Option<super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ItemsPacked {
    #[prost(string, tag = "1")]
    pub packer_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub packed_at: ::core::option::Option<super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Shipped {
    #[prost(string, tag = "1")]
    pub carrier: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tracking_number: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub shipped_at: ::core::option::Option<super::google::protobuf::Timestamp>,
    /// order items for inventory commit saga
    #[prost(message, repeated, tag = "4")]
    pub items: ::prost::alloc::vec::Vec<LineItem>,
    /// order ID for inventory commit saga
    #[prost(string, tag = "5")]
    pub order_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Delivered {
    #[prost(string, tag = "1")]
    pub signature: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub delivered_at: ::core::option::Option<super::google::protobuf::Timestamp>,
}
/// State (for snapshots)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FulfillmentState {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    /// "pending", "picking", "packing", "shipped", "delivered"
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub tracking_number: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub carrier: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub picker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub packer_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub signature: ::prost::alloc::string::String,
    /// order items for inventory commit
    #[prost(message, repeated, tag = "8")]
    pub items: ::prost::alloc::vec::Vec<LineItem>,
}
// =============================================================================
// Projections
// =============================================================================

/// Receipt projection generated when an order completes
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Receipt {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub customer_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub items: ::prost::alloc::vec::Vec<LineItem>,
    #[prost(int32, tag = "4")]
    pub subtotal_cents: i32,
    #[prost(int32, tag = "5")]
    pub discount_cents: i32,
    #[prost(int32, tag = "6")]
    pub final_total_cents: i32,
    #[prost(string, tag = "7")]
    pub payment_method: ::prost::alloc::string::String,
    #[prost(int32, tag = "8")]
    pub loyalty_points_earned: i32,
    #[prost(message, optional, tag = "9")]
    pub completed_at: ::core::option::Option<super::google::protobuf::Timestamp>,
    /// Human-readable receipt text
    #[prost(string, tag = "10")]
    pub formatted_text: ::prost::alloc::string::String,
}
// =============================================================================
// Inventory Domain - manages stock levels and reservations
// =============================================================================

/// Commands
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InitializeStock {
    #[prost(string, tag = "1")]
    pub product_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub quantity: i32,
    /// triggers LowStockAlert when available < threshold
    #[prost(int32, tag = "3")]
    pub low_stock_threshold: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReceiveStock {
    #[prost(int32, tag = "1")]
    pub quantity: i32,
    /// e.g., purchase order number
    #[prost(string, tag = "2")]
    pub reference: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReserveStock {
    #[prost(int32, tag = "1")]
    pub quantity: i32,
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReleaseReservation {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CommitReservation {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
}
/// Events
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StockInitialized {
    #[prost(string, tag = "1")]
    pub product_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub quantity: i32,
    #[prost(int32, tag = "3")]
    pub low_stock_threshold: i32,
    #[prost(message, optional, tag = "4")]
    pub initialized_at: ::core::option::Option<super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StockReceived {
    #[prost(int32, tag = "1")]
    pub quantity: i32,
    #[prost(int32, tag = "2")]
    pub new_on_hand: i32,
    #[prost(string, tag = "3")]
    pub reference: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub received_at: ::core::option::Option<super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StockReserved {
    #[prost(int32, tag = "1")]
    pub quantity: i32,
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub new_available: i32,
    #[prost(message, optional, tag = "4")]
    pub reserved_at: ::core::option::Option<super::google::protobuf::Timestamp>,
    /// Total reserved after this event (fact, not delta)
    #[prost(int32, tag = "5")]
    pub new_reserved: i32,
    /// Total on_hand after this event (unchanged by reserve)
    #[prost(int32, tag = "6")]
    pub new_on_hand: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReservationReleased {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub quantity: i32,
    #[prost(int32, tag = "3")]
    pub new_available: i32,
    #[prost(message, optional, tag = "4")]
    pub released_at: ::core::option::Option<super::google::protobuf::Timestamp>,
    /// Total reserved after this event (fact, not delta)
    #[prost(int32, tag = "5")]
    pub new_reserved: i32,
    /// Total on_hand after this event (unchanged by release)
    #[prost(int32, tag = "6")]
    pub new_on_hand: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReservationCommitted {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub quantity: i32,
    #[prost(int32, tag = "3")]
    pub new_on_hand: i32,
    #[prost(message, optional, tag = "4")]
    pub committed_at: ::core::option::Option<super::google::protobuf::Timestamp>,
    /// Total reserved after this event (fact, not delta)
    #[prost(int32, tag = "5")]
    pub new_reserved: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LowStockAlert {
    #[prost(string, tag = "1")]
    pub product_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub available: i32,
    #[prost(int32, tag = "3")]
    pub threshold: i32,
    #[prost(message, optional, tag = "4")]
    pub alerted_at: ::core::option::Option<super::google::protobuf::Timestamp>,
}
/// State (for snapshots)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InventoryState {
    #[prost(string, tag = "1")]
    pub product_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub on_hand: i32,
    #[prost(int32, tag = "3")]
    pub reserved: i32,
    #[prost(int32, tag = "4")]
    pub low_stock_threshold: i32,
    /// order_id -> quantity
    #[prost(map = "string, int32", tag = "5")]
    pub reservations: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
}
// @@protoc_insertion_point(module)
