apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: angzarr-python-examples

# Require framework images - provides IMAGE_TAG_* template variables for deploy
requires:
  - path: ../../skaffold.yaml
    configs: [angzarr-build]

build:
  tagPolicy:
    sha256: {}
  local:
    push: true
    useBuildkit: false
    concurrency: 0
  artifacts:
    # Domain Aggregates
    - image: localhost:5001/aggregate-order-py
      context: ../..
      docker:
        dockerfile: examples/python/Containerfile
        target: order

    - image: localhost:5001/aggregate-inventory-py
      context: ../..
      docker:
        dockerfile: examples/python/Containerfile
        target: inventory

    - image: localhost:5001/aggregate-fulfillment-py
      context: ../..
      docker:
        dockerfile: examples/python/Containerfile
        target: fulfillment

    # Sagas
    - image: localhost:5001/saga-order-fulfillment-py
      context: ../..
      docker:
        dockerfile: examples/python/Containerfile
        target: saga-fulfillment

    - image: localhost:5001/saga-order-inventory-py
      context: ../..
      docker:
        dockerfile: examples/python/Containerfile
        target: saga-inventory-reservation

    - image: localhost:5001/saga-fulfillment-inventory-py
      context: ../..
      docker:
        dockerfile: examples/python/Containerfile
        target: sag-fulfillment-inventory

    # Projectors
    - image: localhost:5001/projector-inventory-py
      context: ../..
      docker:
        dockerfile: examples/python/Containerfile
        target: projector-inventory

    # Process Managers
    - image: localhost:5001/process-manager-fulfillment-py
      context: ../..
      docker:
        dockerfile: examples/python/Containerfile
        target: process-manager-fulfillment

deploy:
  helm:
    releases:
      - name: angzarr
        chartPath: ../../deploy/helm/angzarr
        namespace: angzarr
        createNamespace: true
        valuesFiles:
          - ../../deploy/helm/angzarr/values-python.yaml
        setValueTemplates:
          # Framework sidecar images
          images.aggregate.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_aggregate}}"
          images.aggregate.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_aggregate}}"
          images.projector.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_projector}}"
          images.projector.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_projector}}"
          images.saga.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_saga}}"
          images.saga.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_saga}}"
          images.processManager.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_process_manager}}"
          images.processManager.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_process_manager}}"
          images.gateway.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_gateway}}"
          images.gateway.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_gateway}}"
          # Business aggregate images
          applications.business[0].image.repository: "{{.IMAGE_REPO_localhost_5001_aggregate_order_py}}"
          applications.business[0].image.tag: "{{.IMAGE_TAG_localhost_5001_aggregate_order_py}}"
          applications.business[1].image.repository: "{{.IMAGE_REPO_localhost_5001_aggregate_inventory_py}}"
          applications.business[1].image.tag: "{{.IMAGE_TAG_localhost_5001_aggregate_inventory_py}}"
          applications.business[2].image.repository: "{{.IMAGE_REPO_localhost_5001_aggregate_fulfillment_py}}"
          applications.business[2].image.tag: "{{.IMAGE_TAG_localhost_5001_aggregate_fulfillment_py}}"
          # Saga images
          applications.sagas[0].image.repository: "{{.IMAGE_REPO_localhost_5001_saga_order_fulfillment_py}}"
          applications.sagas[0].image.tag: "{{.IMAGE_TAG_localhost_5001_saga_order_fulfillment_py}}"
          applications.sagas[1].image.repository: "{{.IMAGE_REPO_localhost_5001_saga_order_inventory_py}}"
          applications.sagas[1].image.tag: "{{.IMAGE_TAG_localhost_5001_saga_order_inventory_py}}"
          applications.sagas[2].image.repository: "{{.IMAGE_REPO_localhost_5001_saga_fulfillment_inventory_py}}"
          applications.sagas[2].image.tag: "{{.IMAGE_TAG_localhost_5001_saga_fulfillment_inventory_py}}"
          # Process Manager images
          applications.processManagers[0].image.repository: "{{.IMAGE_REPO_localhost_5001_process_manager_fulfillment_py}}"
          applications.processManagers[0].image.tag: "{{.IMAGE_TAG_localhost_5001_process_manager_fulfillment_py}}"
          # Projector images
          applications.projectors[0].image.repository: "{{.IMAGE_REPO_localhost_5001_projector_inventory_py}}"
          applications.projectors[0].image.tag: "{{.IMAGE_TAG_localhost_5001_projector_inventory_py}}"

profiles:
  - name: dev
    activation:
      - command: dev
