apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: angzarr-python-examples

requires:
  - path: ../../skaffold.yaml
    activeProfiles:
      - name: local

build:
  local:
    push: true
    useBuildkit: false
  artifacts:
    - image: localhost:5001/py-customer
      context: .
      docker:
        dockerfile: Containerfile
        target: customer

    - image: localhost:5001/py-transaction
      context: .
      docker:
        dockerfile: Containerfile
        target: transaction

    - image: localhost:5001/py-saga-loyalty
      context: .
      docker:
        dockerfile: Containerfile
        target: saga-loyalty

    - image: localhost:5001/py-projector-receipt
      context: .
      docker:
        dockerfile: Containerfile
        target: projector-receipt

    - image: localhost:5001/py-projector-log-customer
      context: .
      docker:
        dockerfile: Containerfile
        target: projector-log-customer

    - image: localhost:5001/py-projector-log-transaction
      context: .
      docker:
        dockerfile: Containerfile
        target: projector-log-transaction

deploy:
  helm:
    releases:
      - name: angzarr
        chartPath: ../../deploy/helm/angzarr
        namespace: angzarr
        createNamespace: true
        valuesFiles:
          - ../../deploy/helm/angzarr/values-python.yaml
        setValues:
          images.command.repository: localhost:5001/angzarr-command
          images.command.tag: latest
          images.projector.repository: localhost:5001/angzarr-projector
          images.projector.tag: latest
          images.saga.repository: localhost:5001/angzarr-saga
          images.saga.tag: latest
          images.stream.repository: localhost:5001/angzarr-stream
          images.stream.tag: latest
          images.gateway.repository: localhost:5001/angzarr-gateway
          images.gateway.tag: latest
          applications.business[0].image.repository: localhost:5001/py-customer
          applications.business[0].image.tag: latest
          applications.business[1].image.repository: localhost:5001/py-transaction
          applications.business[1].image.tag: latest
          applications.projectors[1].image.repository: localhost:5001/py-projector-receipt
          applications.projectors[1].image.tag: latest
          applications.projectors[2].image.repository: localhost:5001/py-projector-log-customer
          applications.projectors[2].image.tag: latest
          applications.projectors[3].image.repository: localhost:5001/py-projector-log-transaction
          applications.projectors[3].image.tag: latest
          applications.sagas[0].image.repository: localhost:5001/py-saga-loyalty
          applications.sagas[0].image.tag: latest

profiles:
  - name: dev
    activation:
      - command: dev
