apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: angzarr-build

build:
  local:
    # Push to local registry instead of kind load (required for podman)
    push: true
    # Podman natively supports cache mounts without BuildKit
    # Keep false for podman compatibility - cache mounts work directly
    useBuildkit: false
    # Try to import base images from registry to avoid rebuilding
    tryImportMissing: true
  artifacts:
    # Command sidecar - handles commands and event persistence
    - image: localhost:5001/angzarr-entity
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-entity

    # Projector sidecar - handles event projections
    - image: localhost:5001/angzarr-projector
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-projector

    # Saga sidecar - handles saga orchestration
    - image: localhost:5001/angzarr-saga
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-saga

    # Stream service - broadcasts events to subscribers
    - image: localhost:5001/angzarr-stream
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-stream

    # Gateway service - routes commands and streams events
    - image: localhost:5001/angzarr-gateway
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-gateway

# Deploy section removed - each language-specific skaffold defines its own deploy
# See examples/rust/skaffold.yaml, examples/go/skaffold.yaml, etc.
