apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: angzarr-build

build:
  tagPolicy:
    sha256: {}
  local:
    push: true
    useBuildkit: false
    concurrency: 1
  artifacts:
    # Dev targets (default) - fast native builds
    - image: localhost:5001/angzarr-aggregate
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-aggregate-dev

    - image: localhost:5001/angzarr-projector
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-projector-dev

    - image: localhost:5001/angzarr-saga
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-saga-dev

    - image: localhost:5001/angzarr-stream
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-stream-dev

    - image: localhost:5001/angzarr-gateway
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-gateway-dev

profiles:
  # Release profile - slow musl builds, minimal images
  - name: release
    build:
      artifacts:
        - image: localhost:5001/angzarr-aggregate
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-aggregate

        - image: localhost:5001/angzarr-projector
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-projector

        - image: localhost:5001/angzarr-saga
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-saga

        - image: localhost:5001/angzarr-stream
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-stream

        - image: localhost:5001/angzarr-gateway
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-gateway
