apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: angzarr-build

# IMPORTANT: All image builds MUST go through skaffold.
# Do NOT manually build with podman/docker and helm upgrade.
#
# Why: Kind nodes cache images by tag at the containerd level. If you push
# a new image with the same tag (e.g., :latest), the node will continue
# serving the old cached image even after `kubectl rollout restart`.
#
# Skaffold solves this by using content-addressable tags (git commit SHA).
# Each build gets a unique tag, so there's never a cache collision.

build:
  # Use git commit SHA for tags - ensures unique tag per build, avoiding
  # Kind node image cache collisions. Never use sha256 or latest tags.
  tagPolicy:
    gitCommit:
      prefix: "dev-"
      variant: AbbrevCommitSha
  local:
    push: true
    useBuildkit: false
    concurrency: 1
  artifacts:
    # Dev targets (default) - fast native builds
    - image: localhost:5001/angzarr-aggregate
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-aggregate-dev

    - image: localhost:5001/angzarr-projector
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-projector-dev

    - image: localhost:5001/angzarr-saga
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-saga-dev

    - image: localhost:5001/angzarr-process-manager
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-process-manager-dev

    - image: localhost:5001/angzarr-stream
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-stream-dev

    - image: localhost:5001/angzarr-gateway
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-gateway-dev

    - image: localhost:5001/angzarr-log
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-log-dev

    - image: localhost:5001/angzarr-topology
      context: .
      docker:
        dockerfile: Containerfile
        target: angzarr-topology-dev

profiles:
  # Release profile - slow musl builds, minimal images
  - name: release
    build:
      artifacts:
        - image: localhost:5001/angzarr-aggregate
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-aggregate

        - image: localhost:5001/angzarr-projector
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-projector

        - image: localhost:5001/angzarr-saga
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-saga

        - image: localhost:5001/angzarr-process-manager
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-process-manager

        - image: localhost:5001/angzarr-stream
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-stream

        - image: localhost:5001/angzarr-gateway
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-gateway

        - image: localhost:5001/angzarr-log
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-log

        - image: localhost:5001/angzarr-topology
          context: .
          docker:
            dockerfile: Containerfile
            target: angzarr-topology
