# PostgreSQL credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-simple.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-simple.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.password | b64enc | quote }}
