{{- if .Values.immudb.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "angzarr-db-immudb.fullname" . }}
  labels:
    {{- include "angzarr-db-immudb.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.immudb.adminPassword | b64enc | quote }}
{{- end }}
