{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "angzarr-pm.serviceAccountName" . }}
  labels:
    {{- include "angzarr-pm.labels" . | nindent 4 }}
{{- end }}
