// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: angzarr/aggregate.proto

package angzarr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to replay events and compute resulting state
type ReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseSnapshot  *Snapshot              `protobuf:"bytes,1,opt,name=base_snapshot,json=baseSnapshot,proto3" json:"base_snapshot,omitempty"` // Starting state (empty = initial state)
	Events        []*EventPage           `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`                                 // Events to apply in order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_angzarr_aggregate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_aggregate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_angzarr_aggregate_proto_rawDescGZIP(), []int{0}
}

func (x *ReplayRequest) GetBaseSnapshot() *Snapshot {
	if x != nil {
		return x.BaseSnapshot
	}
	return nil
}

func (x *ReplayRequest) GetEvents() []*EventPage {
	if x != nil {
		return x.Events
	}
	return nil
}

// Response with computed state after replay
type ReplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *anypb.Any             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // Resulting state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayResponse) Reset() {
	*x = ReplayResponse{}
	mi := &file_angzarr_aggregate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayResponse) ProtoMessage() {}

func (x *ReplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_aggregate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayResponse.ProtoReflect.Descriptor instead.
func (*ReplayResponse) Descriptor() ([]byte, []int) {
	return file_angzarr_aggregate_proto_rawDescGZIP(), []int{1}
}

func (x *ReplayResponse) GetState() *anypb.Any {
	if x != nil {
		return x.State
	}
	return nil
}

// Response from entity - aggregate events + sync projector results
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        *EventBook             `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`           // Events from the target aggregate
	Projections   []*Projection          `protobuf:"bytes,2,rep,name=projections,proto3" json:"projections,omitempty"` // Synchronous projector results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_angzarr_aggregate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_aggregate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_angzarr_aggregate_proto_rawDescGZIP(), []int{2}
}

func (x *CommandResponse) GetEvents() *EventBook {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *CommandResponse) GetProjections() []*Projection {
	if x != nil {
		return x.Projections
	}
	return nil
}

// client logic requests framework to handle revocation
type RevocationResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EmitSystemRevocation  bool                   `protobuf:"varint,1,opt,name=emit_system_revocation,json=emitSystemRevocation,proto3" json:"emit_system_revocation,omitempty"`        // Emit SagaCompensationFailed event
	SendToDeadLetterQueue bool                   `protobuf:"varint,2,opt,name=send_to_dead_letter_queue,json=sendToDeadLetterQueue,proto3" json:"send_to_dead_letter_queue,omitempty"` // Send to DLQ
	Escalate              bool                   `protobuf:"varint,3,opt,name=escalate,proto3" json:"escalate,omitempty"`                                                              // Flag for alerting/human intervention
	Abort                 bool                   `protobuf:"varint,4,opt,name=abort,proto3" json:"abort,omitempty"`                                                                    // Stop saga chain, propagate error to caller
	Reason                string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                                                                   // Context/reason
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RevocationResponse) Reset() {
	*x = RevocationResponse{}
	mi := &file_angzarr_aggregate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevocationResponse) ProtoMessage() {}

func (x *RevocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_aggregate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevocationResponse.ProtoReflect.Descriptor instead.
func (*RevocationResponse) Descriptor() ([]byte, []int) {
	return file_angzarr_aggregate_proto_rawDescGZIP(), []int{3}
}

func (x *RevocationResponse) GetEmitSystemRevocation() bool {
	if x != nil {
		return x.EmitSystemRevocation
	}
	return false
}

func (x *RevocationResponse) GetSendToDeadLetterQueue() bool {
	if x != nil {
		return x.SendToDeadLetterQueue
	}
	return false
}

func (x *RevocationResponse) GetEscalate() bool {
	if x != nil {
		return x.Escalate
	}
	return false
}

func (x *RevocationResponse) GetAbort() bool {
	if x != nil {
		return x.Abort
	}
	return false
}

func (x *RevocationResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Wrapper response for BusinessLogic.Handle
type BusinessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*BusinessResponse_Events
	//	*BusinessResponse_Revocation
	//	*BusinessResponse_Notification
	Result        isBusinessResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessResponse) Reset() {
	*x = BusinessResponse{}
	mi := &file_angzarr_aggregate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessResponse) ProtoMessage() {}

func (x *BusinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_aggregate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessResponse.ProtoReflect.Descriptor instead.
func (*BusinessResponse) Descriptor() ([]byte, []int) {
	return file_angzarr_aggregate_proto_rawDescGZIP(), []int{4}
}

func (x *BusinessResponse) GetResult() isBusinessResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BusinessResponse) GetEvents() *EventBook {
	if x != nil {
		if x, ok := x.Result.(*BusinessResponse_Events); ok {
			return x.Events
		}
	}
	return nil
}

func (x *BusinessResponse) GetRevocation() *RevocationResponse {
	if x != nil {
		if x, ok := x.Result.(*BusinessResponse_Revocation); ok {
			return x.Revocation
		}
	}
	return nil
}

func (x *BusinessResponse) GetNotification() *Notification {
	if x != nil {
		if x, ok := x.Result.(*BusinessResponse_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

type isBusinessResponse_Result interface {
	isBusinessResponse_Result()
}

type BusinessResponse_Events struct {
	Events *EventBook `protobuf:"bytes,1,opt,name=events,proto3,oneof"` // Business provides compensation events
}

type BusinessResponse_Revocation struct {
	Revocation *RevocationResponse `protobuf:"bytes,2,opt,name=revocation,proto3,oneof"` // Business requests framework action
}

type BusinessResponse_Notification struct {
	Notification *Notification `protobuf:"bytes,3,opt,name=notification,proto3,oneof"` // Forward rejection notification upstream
}

func (*BusinessResponse_Events) isBusinessResponse_Result() {}

func (*BusinessResponse_Revocation) isBusinessResponse_Result() {}

func (*BusinessResponse_Notification) isBusinessResponse_Result() {}

// Request for speculative command execution against temporal state.
type SpeculateAggregateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *CommandBook           `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	PointInTime   *TemporalQuery         `protobuf:"bytes,2,opt,name=point_in_time,json=pointInTime,proto3" json:"point_in_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeculateAggregateRequest) Reset() {
	*x = SpeculateAggregateRequest{}
	mi := &file_angzarr_aggregate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeculateAggregateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeculateAggregateRequest) ProtoMessage() {}

func (x *SpeculateAggregateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_aggregate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeculateAggregateRequest.ProtoReflect.Descriptor instead.
func (*SpeculateAggregateRequest) Descriptor() ([]byte, []int) {
	return file_angzarr_aggregate_proto_rawDescGZIP(), []int{5}
}

func (x *SpeculateAggregateRequest) GetCommand() *CommandBook {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SpeculateAggregateRequest) GetPointInTime() *TemporalQuery {
	if x != nil {
		return x.PointInTime
	}
	return nil
}

var File_angzarr_aggregate_proto protoreflect.FileDescriptor

const file_angzarr_aggregate_proto_rawDesc = "" +
	"\n" +
	"\x17angzarr/aggregate.proto\x12\aangzarr\x1a\x13angzarr/types.proto\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"s\n" +
	"\rReplayRequest\x126\n" +
	"\rbase_snapshot\x18\x01 \x01(\v2\x11.angzarr.SnapshotR\fbaseSnapshot\x12*\n" +
	"\x06events\x18\x02 \x03(\v2\x12.angzarr.EventPageR\x06events\"<\n" +
	"\x0eReplayResponse\x12*\n" +
	"\x05state\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x05state\"t\n" +
	"\x0fCommandResponse\x12*\n" +
	"\x06events\x18\x01 \x01(\v2\x12.angzarr.EventBookR\x06events\x125\n" +
	"\vprojections\x18\x02 \x03(\v2\x13.angzarr.ProjectionR\vprojections\"\xce\x01\n" +
	"\x12RevocationResponse\x124\n" +
	"\x16emit_system_revocation\x18\x01 \x01(\bR\x14emitSystemRevocation\x128\n" +
	"\x19send_to_dead_letter_queue\x18\x02 \x01(\bR\x15sendToDeadLetterQueue\x12\x1a\n" +
	"\bescalate\x18\x03 \x01(\bR\bescalate\x12\x14\n" +
	"\x05abort\x18\x04 \x01(\bR\x05abort\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xc6\x01\n" +
	"\x10BusinessResponse\x12,\n" +
	"\x06events\x18\x01 \x01(\v2\x12.angzarr.EventBookH\x00R\x06events\x12=\n" +
	"\n" +
	"revocation\x18\x02 \x01(\v2\x1b.angzarr.RevocationResponseH\x00R\n" +
	"revocation\x12;\n" +
	"\fnotification\x18\x03 \x01(\v2\x15.angzarr.NotificationH\x00R\fnotificationB\b\n" +
	"\x06result\"\x87\x01\n" +
	"\x19SpeculateAggregateRequest\x12.\n" +
	"\acommand\x18\x01 \x01(\v2\x14.angzarr.CommandBookR\acommand\x12:\n" +
	"\rpoint_in_time\x18\x02 \x01(\v2\x16.angzarr.TemporalQueryR\vpointInTime2\x8e\x01\n" +
	"\x10AggregateService\x12?\n" +
	"\x06Handle\x12\x1a.angzarr.ContextualCommand\x1a\x19.angzarr.BusinessResponse\x129\n" +
	"\x06Replay\x12\x16.angzarr.ReplayRequest\x1a\x17.angzarr.ReplayResponse2\xf0\x01\n" +
	"\x1bAggregateCoordinatorService\x128\n" +
	"\x06Handle\x12\x14.angzarr.CommandBook\x1a\x18.angzarr.CommandResponse\x12@\n" +
	"\n" +
	"HandleSync\x12\x18.angzarr.SyncCommandBook\x1a\x18.angzarr.CommandResponse\x12U\n" +
	"\x15HandleSyncSpeculative\x12\".angzarr.SpeculateAggregateRequest\x1a\x18.angzarr.CommandResponseB\x94\x01\n" +
	"\vcom.angzarrB\x0eAggregateProtoP\x01Z9github.com/benjaminabbitt/angzarr/client/go/proto/angzarr\xa2\x02\x03AXX\xaa\x02\aAngzarr\xca\x02\aAngzarr\xe2\x02\x13Angzarr\\GPBMetadata\xea\x02\aAngzarrb\x06proto3"

var (
	file_angzarr_aggregate_proto_rawDescOnce sync.Once
	file_angzarr_aggregate_proto_rawDescData []byte
)

func file_angzarr_aggregate_proto_rawDescGZIP() []byte {
	file_angzarr_aggregate_proto_rawDescOnce.Do(func() {
		file_angzarr_aggregate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_angzarr_aggregate_proto_rawDesc), len(file_angzarr_aggregate_proto_rawDesc)))
	})
	return file_angzarr_aggregate_proto_rawDescData
}

var file_angzarr_aggregate_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_angzarr_aggregate_proto_goTypes = []any{
	(*ReplayRequest)(nil),             // 0: angzarr.ReplayRequest
	(*ReplayResponse)(nil),            // 1: angzarr.ReplayResponse
	(*CommandResponse)(nil),           // 2: angzarr.CommandResponse
	(*RevocationResponse)(nil),        // 3: angzarr.RevocationResponse
	(*BusinessResponse)(nil),          // 4: angzarr.BusinessResponse
	(*SpeculateAggregateRequest)(nil), // 5: angzarr.SpeculateAggregateRequest
	(*Snapshot)(nil),                  // 6: angzarr.Snapshot
	(*EventPage)(nil),                 // 7: angzarr.EventPage
	(*anypb.Any)(nil),                 // 8: google.protobuf.Any
	(*EventBook)(nil),                 // 9: angzarr.EventBook
	(*Projection)(nil),                // 10: angzarr.Projection
	(*Notification)(nil),              // 11: angzarr.Notification
	(*CommandBook)(nil),               // 12: angzarr.CommandBook
	(*TemporalQuery)(nil),             // 13: angzarr.TemporalQuery
	(*ContextualCommand)(nil),         // 14: angzarr.ContextualCommand
	(*SyncCommandBook)(nil),           // 15: angzarr.SyncCommandBook
}
var file_angzarr_aggregate_proto_depIdxs = []int32{
	6,  // 0: angzarr.ReplayRequest.base_snapshot:type_name -> angzarr.Snapshot
	7,  // 1: angzarr.ReplayRequest.events:type_name -> angzarr.EventPage
	8,  // 2: angzarr.ReplayResponse.state:type_name -> google.protobuf.Any
	9,  // 3: angzarr.CommandResponse.events:type_name -> angzarr.EventBook
	10, // 4: angzarr.CommandResponse.projections:type_name -> angzarr.Projection
	9,  // 5: angzarr.BusinessResponse.events:type_name -> angzarr.EventBook
	3,  // 6: angzarr.BusinessResponse.revocation:type_name -> angzarr.RevocationResponse
	11, // 7: angzarr.BusinessResponse.notification:type_name -> angzarr.Notification
	12, // 8: angzarr.SpeculateAggregateRequest.command:type_name -> angzarr.CommandBook
	13, // 9: angzarr.SpeculateAggregateRequest.point_in_time:type_name -> angzarr.TemporalQuery
	14, // 10: angzarr.AggregateService.Handle:input_type -> angzarr.ContextualCommand
	0,  // 11: angzarr.AggregateService.Replay:input_type -> angzarr.ReplayRequest
	12, // 12: angzarr.AggregateCoordinatorService.Handle:input_type -> angzarr.CommandBook
	15, // 13: angzarr.AggregateCoordinatorService.HandleSync:input_type -> angzarr.SyncCommandBook
	5,  // 14: angzarr.AggregateCoordinatorService.HandleSyncSpeculative:input_type -> angzarr.SpeculateAggregateRequest
	4,  // 15: angzarr.AggregateService.Handle:output_type -> angzarr.BusinessResponse
	1,  // 16: angzarr.AggregateService.Replay:output_type -> angzarr.ReplayResponse
	2,  // 17: angzarr.AggregateCoordinatorService.Handle:output_type -> angzarr.CommandResponse
	2,  // 18: angzarr.AggregateCoordinatorService.HandleSync:output_type -> angzarr.CommandResponse
	2,  // 19: angzarr.AggregateCoordinatorService.HandleSyncSpeculative:output_type -> angzarr.CommandResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_angzarr_aggregate_proto_init() }
func file_angzarr_aggregate_proto_init() {
	if File_angzarr_aggregate_proto != nil {
		return
	}
	file_angzarr_types_proto_init()
	file_angzarr_aggregate_proto_msgTypes[4].OneofWrappers = []any{
		(*BusinessResponse_Events)(nil),
		(*BusinessResponse_Revocation)(nil),
		(*BusinessResponse_Notification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_angzarr_aggregate_proto_rawDesc), len(file_angzarr_aggregate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_angzarr_aggregate_proto_goTypes,
		DependencyIndexes: file_angzarr_aggregate_proto_depIdxs,
		MessageInfos:      file_angzarr_aggregate_proto_msgTypes,
	}.Build()
	File_angzarr_aggregate_proto = out.File
	file_angzarr_aggregate_proto_goTypes = nil
	file_angzarr_aggregate_proto_depIdxs = nil
}
