// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: angzarr/aggregate.proto

package angzarr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AggregateService_GetDescriptor_FullMethodName = "/angzarr.AggregateService/GetDescriptor"
	AggregateService_Handle_FullMethodName        = "/angzarr.AggregateService/Handle"
)

// AggregateServiceClient is the client API for AggregateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AggregateService: client logic that processes commands and emits events
// Also known as Command Handler in CQRS terminology
// client logic doesn't care about sync - coordinator decides
type AggregateServiceClient interface {
	// Self-description: component type, subscribed domains, handled command types
	GetDescriptor(ctx context.Context, in *GetDescriptorRequest, opts ...grpc.CallOption) (*ComponentDescriptor, error)
	Handle(ctx context.Context, in *ContextualCommand, opts ...grpc.CallOption) (*BusinessResponse, error)
}

type aggregateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregateServiceClient(cc grpc.ClientConnInterface) AggregateServiceClient {
	return &aggregateServiceClient{cc}
}

func (c *aggregateServiceClient) GetDescriptor(ctx context.Context, in *GetDescriptorRequest, opts ...grpc.CallOption) (*ComponentDescriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComponentDescriptor)
	err := c.cc.Invoke(ctx, AggregateService_GetDescriptor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregateServiceClient) Handle(ctx context.Context, in *ContextualCommand, opts ...grpc.CallOption) (*BusinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BusinessResponse)
	err := c.cc.Invoke(ctx, AggregateService_Handle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregateServiceServer is the server API for AggregateService service.
// All implementations must embed UnimplementedAggregateServiceServer
// for forward compatibility.
//
// AggregateService: client logic that processes commands and emits events
// Also known as Command Handler in CQRS terminology
// client logic doesn't care about sync - coordinator decides
type AggregateServiceServer interface {
	// Self-description: component type, subscribed domains, handled command types
	GetDescriptor(context.Context, *GetDescriptorRequest) (*ComponentDescriptor, error)
	Handle(context.Context, *ContextualCommand) (*BusinessResponse, error)
	mustEmbedUnimplementedAggregateServiceServer()
}

// UnimplementedAggregateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAggregateServiceServer struct{}

func (UnimplementedAggregateServiceServer) GetDescriptor(context.Context, *GetDescriptorRequest) (*ComponentDescriptor, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDescriptor not implemented")
}
func (UnimplementedAggregateServiceServer) Handle(context.Context, *ContextualCommand) (*BusinessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedAggregateServiceServer) mustEmbedUnimplementedAggregateServiceServer() {}
func (UnimplementedAggregateServiceServer) testEmbeddedByValue()                          {}

// UnsafeAggregateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregateServiceServer will
// result in compilation errors.
type UnsafeAggregateServiceServer interface {
	mustEmbedUnimplementedAggregateServiceServer()
}

func RegisterAggregateServiceServer(s grpc.ServiceRegistrar, srv AggregateServiceServer) {
	// If the following call panics, it indicates UnimplementedAggregateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AggregateService_ServiceDesc, srv)
}

func _AggregateService_GetDescriptor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDescriptorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateServiceServer).GetDescriptor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregateService_GetDescriptor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateServiceServer).GetDescriptor(ctx, req.(*GetDescriptorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregateService_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextualCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateServiceServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregateService_Handle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateServiceServer).Handle(ctx, req.(*ContextualCommand))
	}
	return interceptor(ctx, in, info, handler)
}

// AggregateService_ServiceDesc is the grpc.ServiceDesc for AggregateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AggregateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "angzarr.AggregateService",
	HandlerType: (*AggregateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDescriptor",
			Handler:    _AggregateService_GetDescriptor_Handler,
		},
		{
			MethodName: "Handle",
			Handler:    _AggregateService_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "angzarr/aggregate.proto",
}

const (
	AggregateCoordinatorService_Handle_FullMethodName       = "/angzarr.AggregateCoordinatorService/Handle"
	AggregateCoordinatorService_HandleSync_FullMethodName   = "/angzarr.AggregateCoordinatorService/HandleSync"
	AggregateCoordinatorService_DryRunHandle_FullMethodName = "/angzarr.AggregateCoordinatorService/DryRunHandle"
)

// AggregateCoordinatorServiceClient is the client API for AggregateCoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AggregateCoordinatorService: orchestrates command processing for aggregates
type AggregateCoordinatorServiceClient interface {
	// Async processing - fire and forget
	Handle(ctx context.Context, in *CommandBook, opts ...grpc.CallOption) (*CommandResponse, error)
	// Sync processing - waits for completion based on sync_mode
	HandleSync(ctx context.Context, in *SyncCommandBook, opts ...grpc.CallOption) (*CommandResponse, error)
	// Dry-run: execute against temporal state without persisting.
	DryRunHandle(ctx context.Context, in *DryRunRequest, opts ...grpc.CallOption) (*CommandResponse, error)
}

type aggregateCoordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregateCoordinatorServiceClient(cc grpc.ClientConnInterface) AggregateCoordinatorServiceClient {
	return &aggregateCoordinatorServiceClient{cc}
}

func (c *aggregateCoordinatorServiceClient) Handle(ctx context.Context, in *CommandBook, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, AggregateCoordinatorService_Handle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregateCoordinatorServiceClient) HandleSync(ctx context.Context, in *SyncCommandBook, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, AggregateCoordinatorService_HandleSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregateCoordinatorServiceClient) DryRunHandle(ctx context.Context, in *DryRunRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, AggregateCoordinatorService_DryRunHandle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregateCoordinatorServiceServer is the server API for AggregateCoordinatorService service.
// All implementations must embed UnimplementedAggregateCoordinatorServiceServer
// for forward compatibility.
//
// AggregateCoordinatorService: orchestrates command processing for aggregates
type AggregateCoordinatorServiceServer interface {
	// Async processing - fire and forget
	Handle(context.Context, *CommandBook) (*CommandResponse, error)
	// Sync processing - waits for completion based on sync_mode
	HandleSync(context.Context, *SyncCommandBook) (*CommandResponse, error)
	// Dry-run: execute against temporal state without persisting.
	DryRunHandle(context.Context, *DryRunRequest) (*CommandResponse, error)
	mustEmbedUnimplementedAggregateCoordinatorServiceServer()
}

// UnimplementedAggregateCoordinatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAggregateCoordinatorServiceServer struct{}

func (UnimplementedAggregateCoordinatorServiceServer) Handle(context.Context, *CommandBook) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedAggregateCoordinatorServiceServer) HandleSync(context.Context, *SyncCommandBook) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleSync not implemented")
}
func (UnimplementedAggregateCoordinatorServiceServer) DryRunHandle(context.Context, *DryRunRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DryRunHandle not implemented")
}
func (UnimplementedAggregateCoordinatorServiceServer) mustEmbedUnimplementedAggregateCoordinatorServiceServer() {
}
func (UnimplementedAggregateCoordinatorServiceServer) testEmbeddedByValue() {}

// UnsafeAggregateCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregateCoordinatorServiceServer will
// result in compilation errors.
type UnsafeAggregateCoordinatorServiceServer interface {
	mustEmbedUnimplementedAggregateCoordinatorServiceServer()
}

func RegisterAggregateCoordinatorServiceServer(s grpc.ServiceRegistrar, srv AggregateCoordinatorServiceServer) {
	// If the following call panics, it indicates UnimplementedAggregateCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AggregateCoordinatorService_ServiceDesc, srv)
}

func _AggregateCoordinatorService_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateCoordinatorServiceServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregateCoordinatorService_Handle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateCoordinatorServiceServer).Handle(ctx, req.(*CommandBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregateCoordinatorService_HandleSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncCommandBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateCoordinatorServiceServer).HandleSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregateCoordinatorService_HandleSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateCoordinatorServiceServer).HandleSync(ctx, req.(*SyncCommandBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregateCoordinatorService_DryRunHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DryRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateCoordinatorServiceServer).DryRunHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregateCoordinatorService_DryRunHandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateCoordinatorServiceServer).DryRunHandle(ctx, req.(*DryRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AggregateCoordinatorService_ServiceDesc is the grpc.ServiceDesc for AggregateCoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AggregateCoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "angzarr.AggregateCoordinatorService",
	HandlerType: (*AggregateCoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _AggregateCoordinatorService_Handle_Handler,
		},
		{
			MethodName: "HandleSync",
			Handler:    _AggregateCoordinatorService_HandleSync_Handler,
		},
		{
			MethodName: "DryRunHandle",
			Handler:    _AggregateCoordinatorService_DryRunHandle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "angzarr/aggregate.proto",
}

const (
	SpeculativeService_DryRunCommand_FullMethodName           = "/angzarr.SpeculativeService/DryRunCommand"
	SpeculativeService_SpeculateProjector_FullMethodName      = "/angzarr.SpeculativeService/SpeculateProjector"
	SpeculativeService_SpeculateSaga_FullMethodName           = "/angzarr.SpeculativeService/SpeculateSaga"
	SpeculativeService_SpeculateProcessManager_FullMethodName = "/angzarr.SpeculativeService/SpeculateProcessManager"
)

// SpeculativeServiceClient is the client API for SpeculativeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Speculative execution service - execute without persisting side effects.
// Supports "what-if" scenarios for commands, projectors, sagas, and process managers.
type SpeculativeServiceClient interface {
	// Execute command against temporal state without persisting.
	// Returns speculative events only — no side effects.
	DryRunCommand(ctx context.Context, in *DryRunRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// Execute projector against provided events without persisting.
	// Returns projection result.
	SpeculateProjector(ctx context.Context, in *SpeculateProjectorRequest, opts ...grpc.CallOption) (*Projection, error)
	// Execute saga against provided events without persisting.
	// Returns commands that would be produced.
	SpeculateSaga(ctx context.Context, in *SpeculateSagaRequest, opts ...grpc.CallOption) (*SagaResponse, error)
	// Execute process manager against provided context without persisting.
	// Returns commands and PM events that would be produced.
	SpeculateProcessManager(ctx context.Context, in *SpeculatePmRequest, opts ...grpc.CallOption) (*ProcessManagerHandleResponse, error)
}

type speculativeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeculativeServiceClient(cc grpc.ClientConnInterface) SpeculativeServiceClient {
	return &speculativeServiceClient{cc}
}

func (c *speculativeServiceClient) DryRunCommand(ctx context.Context, in *DryRunRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, SpeculativeService_DryRunCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speculativeServiceClient) SpeculateProjector(ctx context.Context, in *SpeculateProjectorRequest, opts ...grpc.CallOption) (*Projection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Projection)
	err := c.cc.Invoke(ctx, SpeculativeService_SpeculateProjector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speculativeServiceClient) SpeculateSaga(ctx context.Context, in *SpeculateSagaRequest, opts ...grpc.CallOption) (*SagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SagaResponse)
	err := c.cc.Invoke(ctx, SpeculativeService_SpeculateSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speculativeServiceClient) SpeculateProcessManager(ctx context.Context, in *SpeculatePmRequest, opts ...grpc.CallOption) (*ProcessManagerHandleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessManagerHandleResponse)
	err := c.cc.Invoke(ctx, SpeculativeService_SpeculateProcessManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpeculativeServiceServer is the server API for SpeculativeService service.
// All implementations must embed UnimplementedSpeculativeServiceServer
// for forward compatibility.
//
// Speculative execution service - execute without persisting side effects.
// Supports "what-if" scenarios for commands, projectors, sagas, and process managers.
type SpeculativeServiceServer interface {
	// Execute command against temporal state without persisting.
	// Returns speculative events only — no side effects.
	DryRunCommand(context.Context, *DryRunRequest) (*CommandResponse, error)
	// Execute projector against provided events without persisting.
	// Returns projection result.
	SpeculateProjector(context.Context, *SpeculateProjectorRequest) (*Projection, error)
	// Execute saga against provided events without persisting.
	// Returns commands that would be produced.
	SpeculateSaga(context.Context, *SpeculateSagaRequest) (*SagaResponse, error)
	// Execute process manager against provided context without persisting.
	// Returns commands and PM events that would be produced.
	SpeculateProcessManager(context.Context, *SpeculatePmRequest) (*ProcessManagerHandleResponse, error)
	mustEmbedUnimplementedSpeculativeServiceServer()
}

// UnimplementedSpeculativeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpeculativeServiceServer struct{}

func (UnimplementedSpeculativeServiceServer) DryRunCommand(context.Context, *DryRunRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DryRunCommand not implemented")
}
func (UnimplementedSpeculativeServiceServer) SpeculateProjector(context.Context, *SpeculateProjectorRequest) (*Projection, error) {
	return nil, status.Error(codes.Unimplemented, "method SpeculateProjector not implemented")
}
func (UnimplementedSpeculativeServiceServer) SpeculateSaga(context.Context, *SpeculateSagaRequest) (*SagaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpeculateSaga not implemented")
}
func (UnimplementedSpeculativeServiceServer) SpeculateProcessManager(context.Context, *SpeculatePmRequest) (*ProcessManagerHandleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpeculateProcessManager not implemented")
}
func (UnimplementedSpeculativeServiceServer) mustEmbedUnimplementedSpeculativeServiceServer() {}
func (UnimplementedSpeculativeServiceServer) testEmbeddedByValue()                            {}

// UnsafeSpeculativeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeculativeServiceServer will
// result in compilation errors.
type UnsafeSpeculativeServiceServer interface {
	mustEmbedUnimplementedSpeculativeServiceServer()
}

func RegisterSpeculativeServiceServer(s grpc.ServiceRegistrar, srv SpeculativeServiceServer) {
	// If the following call panics, it indicates UnimplementedSpeculativeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpeculativeService_ServiceDesc, srv)
}

func _SpeculativeService_DryRunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DryRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeculativeServiceServer).DryRunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeculativeService_DryRunCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeculativeServiceServer).DryRunCommand(ctx, req.(*DryRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeculativeService_SpeculateProjector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpeculateProjectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeculativeServiceServer).SpeculateProjector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeculativeService_SpeculateProjector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeculativeServiceServer).SpeculateProjector(ctx, req.(*SpeculateProjectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeculativeService_SpeculateSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpeculateSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeculativeServiceServer).SpeculateSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeculativeService_SpeculateSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeculativeServiceServer).SpeculateSaga(ctx, req.(*SpeculateSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeculativeService_SpeculateProcessManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpeculatePmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeculativeServiceServer).SpeculateProcessManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeculativeService_SpeculateProcessManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeculativeServiceServer).SpeculateProcessManager(ctx, req.(*SpeculatePmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpeculativeService_ServiceDesc is the grpc.ServiceDesc for SpeculativeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpeculativeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "angzarr.SpeculativeService",
	HandlerType: (*SpeculativeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DryRunCommand",
			Handler:    _SpeculativeService_DryRunCommand_Handler,
		},
		{
			MethodName: "SpeculateProjector",
			Handler:    _SpeculativeService_SpeculateProjector_Handler,
		},
		{
			MethodName: "SpeculateSaga",
			Handler:    _SpeculativeService_SpeculateSaga_Handler,
		},
		{
			MethodName: "SpeculateProcessManager",
			Handler:    _SpeculativeService_SpeculateProcessManager_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "angzarr/aggregate.proto",
}
