// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: angzarr/cloudevents.proto

package angzarr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// docs:start:cloud_event
// CloudEvent represents a single event for external consumption.
//
// Client projectors create these by filtering/transforming internal events.
// Framework fills envelope fields (id, source, time) from Cover/EventPage
// if not explicitly set by the client.
//
// The `data` field is a protobuf Any that framework converts to JSON via
// prost-reflect using the descriptor pool. Clients should pack a "public"
// proto message that omits sensitive fields.
type CloudEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type (e.g., "com.example.order.created").
	// Default: proto type_url suffix from original event.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Event payload as proto Any.
	// Framework converts to JSON for CloudEvents output.
	// Client should filter sensitive fields before packing.
	Data *anypb.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Custom extension attributes.
	// Keys should follow CloudEvents naming (lowercase, no dots).
	// Framework adds correlationid automatically if present in Cover.
	Extensions map[string]string `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional overrides. Framework uses Cover/EventPage values if not set.
	Id            *string `protobuf:"bytes,4,opt,name=id,proto3,oneof" json:"id,omitempty"`           // Default: {domain}:{root_id}:{sequence}
	Source        *string `protobuf:"bytes,5,opt,name=source,proto3,oneof" json:"source,omitempty"`   // Default: angzarr/{domain}
	Subject       *string `protobuf:"bytes,6,opt,name=subject,proto3,oneof" json:"subject,omitempty"` // Default: aggregate root ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudEvent) Reset() {
	*x = CloudEvent{}
	mi := &file_angzarr_cloudevents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudEvent) ProtoMessage() {}

func (x *CloudEvent) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_cloudevents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudEvent.ProtoReflect.Descriptor instead.
func (*CloudEvent) Descriptor() ([]byte, []int) {
	return file_angzarr_cloudevents_proto_rawDescGZIP(), []int{0}
}

func (x *CloudEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CloudEvent) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CloudEvent) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *CloudEvent) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CloudEvent) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *CloudEvent) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

// CloudEventsResponse is returned by client projectors in Projection.projection.
//
// Framework detects this type by checking projection.type_url and routes
// the events to configured sinks (HTTP webhook, Kafka).
//
// Client may return 0 events (skip), 1 event (typical), or N events
// (fan-out scenarios like multi-tenant notifications).
type CloudEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*CloudEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudEventsResponse) Reset() {
	*x = CloudEventsResponse{}
	mi := &file_angzarr_cloudevents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudEventsResponse) ProtoMessage() {}

func (x *CloudEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_cloudevents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudEventsResponse.ProtoReflect.Descriptor instead.
func (*CloudEventsResponse) Descriptor() ([]byte, []int) {
	return file_angzarr_cloudevents_proto_rawDescGZIP(), []int{1}
}

func (x *CloudEventsResponse) GetEvents() []*CloudEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_angzarr_cloudevents_proto protoreflect.FileDescriptor

const file_angzarr_cloudevents_proto_rawDesc = "" +
	"\n" +
	"\x19angzarr/cloudevents.proto\x12\aangzarr\x1a\x19google/protobuf/any.proto\"\xbd\x02\n" +
	"\n" +
	"CloudEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04data\x12C\n" +
	"\n" +
	"extensions\x18\x03 \x03(\v2#.angzarr.CloudEvent.ExtensionsEntryR\n" +
	"extensions\x12\x13\n" +
	"\x02id\x18\x04 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x05 \x01(\tH\x01R\x06source\x88\x01\x01\x12\x1d\n" +
	"\asubject\x18\x06 \x01(\tH\x02R\asubject\x88\x01\x01\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x05\n" +
	"\x03_idB\t\n" +
	"\a_sourceB\n" +
	"\n" +
	"\b_subject\"B\n" +
	"\x13CloudEventsResponse\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.angzarr.CloudEventR\x06eventsB\x96\x01\n" +
	"\vcom.angzarrB\x10CloudeventsProtoP\x01Z9github.com/benjaminabbitt/angzarr/client/go/proto/angzarr\xa2\x02\x03AXX\xaa\x02\aAngzarr\xca\x02\aAngzarr\xe2\x02\x13Angzarr\\GPBMetadata\xea\x02\aAngzarrb\x06proto3"

var (
	file_angzarr_cloudevents_proto_rawDescOnce sync.Once
	file_angzarr_cloudevents_proto_rawDescData []byte
)

func file_angzarr_cloudevents_proto_rawDescGZIP() []byte {
	file_angzarr_cloudevents_proto_rawDescOnce.Do(func() {
		file_angzarr_cloudevents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_angzarr_cloudevents_proto_rawDesc), len(file_angzarr_cloudevents_proto_rawDesc)))
	})
	return file_angzarr_cloudevents_proto_rawDescData
}

var file_angzarr_cloudevents_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_angzarr_cloudevents_proto_goTypes = []any{
	(*CloudEvent)(nil),          // 0: angzarr.CloudEvent
	(*CloudEventsResponse)(nil), // 1: angzarr.CloudEventsResponse
	nil,                         // 2: angzarr.CloudEvent.ExtensionsEntry
	(*anypb.Any)(nil),           // 3: google.protobuf.Any
}
var file_angzarr_cloudevents_proto_depIdxs = []int32{
	3, // 0: angzarr.CloudEvent.data:type_name -> google.protobuf.Any
	2, // 1: angzarr.CloudEvent.extensions:type_name -> angzarr.CloudEvent.ExtensionsEntry
	0, // 2: angzarr.CloudEventsResponse.events:type_name -> angzarr.CloudEvent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_angzarr_cloudevents_proto_init() }
func file_angzarr_cloudevents_proto_init() {
	if File_angzarr_cloudevents_proto != nil {
		return
	}
	file_angzarr_cloudevents_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_angzarr_cloudevents_proto_rawDesc), len(file_angzarr_cloudevents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_angzarr_cloudevents_proto_goTypes,
		DependencyIndexes: file_angzarr_cloudevents_proto_depIdxs,
		MessageInfos:      file_angzarr_cloudevents_proto_msgTypes,
	}.Build()
	File_angzarr_cloudevents_proto = out.File
	file_angzarr_cloudevents_proto_goTypes = nil
	file_angzarr_cloudevents_proto_depIdxs = nil
}
