// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: angzarr/process_manager.proto

package angzarr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for speculative PM execution at a point in time.
type SpeculatePmRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Request       *ProcessManagerHandleRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	PointInTime   *TemporalQuery               `protobuf:"bytes,2,opt,name=point_in_time,json=pointInTime,proto3" json:"point_in_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeculatePmRequest) Reset() {
	*x = SpeculatePmRequest{}
	mi := &file_angzarr_process_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeculatePmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeculatePmRequest) ProtoMessage() {}

func (x *SpeculatePmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_process_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeculatePmRequest.ProtoReflect.Descriptor instead.
func (*SpeculatePmRequest) Descriptor() ([]byte, []int) {
	return file_angzarr_process_manager_proto_rawDescGZIP(), []int{0}
}

func (x *SpeculatePmRequest) GetRequest() *ProcessManagerHandleRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *SpeculatePmRequest) GetPointInTime() *TemporalQuery {
	if x != nil {
		return x.PointInTime
	}
	return nil
}

// Phase 1 request: PM declares additional destinations needed.
type ProcessManagerPrepareRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full state of triggering domain (by correlation_id).
	Trigger *EventBook `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	// Current process manager state (by correlation_id). May be empty for new workflow.
	ProcessState  *EventBook `protobuf:"bytes,2,opt,name=process_state,json=processState,proto3" json:"process_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessManagerPrepareRequest) Reset() {
	*x = ProcessManagerPrepareRequest{}
	mi := &file_angzarr_process_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessManagerPrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessManagerPrepareRequest) ProtoMessage() {}

func (x *ProcessManagerPrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_process_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessManagerPrepareRequest.ProtoReflect.Descriptor instead.
func (*ProcessManagerPrepareRequest) Descriptor() ([]byte, []int) {
	return file_angzarr_process_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessManagerPrepareRequest) GetTrigger() *EventBook {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *ProcessManagerPrepareRequest) GetProcessState() *EventBook {
	if x != nil {
		return x.ProcessState
	}
	return nil
}

// Phase 1 response: destinations to fetch before Handle.
type ProcessManagerPrepareResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Additional aggregates needed beyond trigger. Query by correlation_id.
	// Minimize fetches - only declare what's actually needed.
	Destinations  []*Cover `protobuf:"bytes,1,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessManagerPrepareResponse) Reset() {
	*x = ProcessManagerPrepareResponse{}
	mi := &file_angzarr_process_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessManagerPrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessManagerPrepareResponse) ProtoMessage() {}

func (x *ProcessManagerPrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_process_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessManagerPrepareResponse.ProtoReflect.Descriptor instead.
func (*ProcessManagerPrepareResponse) Descriptor() ([]byte, []int) {
	return file_angzarr_process_manager_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessManagerPrepareResponse) GetDestinations() []*Cover {
	if x != nil {
		return x.Destinations
	}
	return nil
}

// Phase 2 request: full context for PM decision.
type ProcessManagerHandleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full state of triggering domain.
	Trigger *EventBook `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	// Current process manager state (event-sourced).
	ProcessState *EventBook `protobuf:"bytes,2,opt,name=process_state,json=processState,proto3" json:"process_state,omitempty"`
	// Additional destinations fetched per Prepare response.
	Destinations  []*EventBook `protobuf:"bytes,3,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessManagerHandleRequest) Reset() {
	*x = ProcessManagerHandleRequest{}
	mi := &file_angzarr_process_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessManagerHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessManagerHandleRequest) ProtoMessage() {}

func (x *ProcessManagerHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_process_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessManagerHandleRequest.ProtoReflect.Descriptor instead.
func (*ProcessManagerHandleRequest) Descriptor() ([]byte, []int) {
	return file_angzarr_process_manager_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessManagerHandleRequest) GetTrigger() *EventBook {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *ProcessManagerHandleRequest) GetProcessState() *EventBook {
	if x != nil {
		return x.ProcessState
	}
	return nil
}

func (x *ProcessManagerHandleRequest) GetDestinations() []*EventBook {
	if x != nil {
		return x.Destinations
	}
	return nil
}

// Phase 2 response: commands and PM events.
type ProcessManagerHandleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Commands to issue to other aggregates.
	Commands []*CommandBook `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	// Events for the process manager's own domain (non-duplicative workflow state).
	// These are persisted via AggregateCoordinator to the PM's domain.
	ProcessEvents *EventBook `protobuf:"bytes,2,opt,name=process_events,json=processEvents,proto3" json:"process_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessManagerHandleResponse) Reset() {
	*x = ProcessManagerHandleResponse{}
	mi := &file_angzarr_process_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessManagerHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessManagerHandleResponse) ProtoMessage() {}

func (x *ProcessManagerHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_process_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessManagerHandleResponse.ProtoReflect.Descriptor instead.
func (*ProcessManagerHandleResponse) Descriptor() ([]byte, []int) {
	return file_angzarr_process_manager_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessManagerHandleResponse) GetCommands() []*CommandBook {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *ProcessManagerHandleResponse) GetProcessEvents() *EventBook {
	if x != nil {
		return x.ProcessEvents
	}
	return nil
}

// System event for process timeout - emitted by TimeoutScheduler.
type ProcessTimeout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ProcessType   string                 `protobuf:"bytes,2,opt,name=process_type,json=processType,proto3" json:"process_type,omitempty"` // e.g., "order-fulfillment"
	TimeoutType   string                 `protobuf:"bytes,3,opt,name=timeout_type,json=timeoutType,proto3" json:"timeout_type,omitempty"` // e.g., "payment", "reservation"
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTimeout) Reset() {
	*x = ProcessTimeout{}
	mi := &file_angzarr_process_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTimeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTimeout) ProtoMessage() {}

func (x *ProcessTimeout) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_process_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTimeout.ProtoReflect.Descriptor instead.
func (*ProcessTimeout) Descriptor() ([]byte, []int) {
	return file_angzarr_process_manager_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessTimeout) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ProcessTimeout) GetProcessType() string {
	if x != nil {
		return x.ProcessType
	}
	return ""
}

func (x *ProcessTimeout) GetTimeoutType() string {
	if x != nil {
		return x.TimeoutType
	}
	return ""
}

func (x *ProcessTimeout) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

var File_angzarr_process_manager_proto protoreflect.FileDescriptor

const file_angzarr_process_manager_proto_rawDesc = "" +
	"\n" +
	"\x1dangzarr/process_manager.proto\x12\aangzarr\x1a\x13angzarr/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n" +
	"\x12SpeculatePmRequest\x12>\n" +
	"\arequest\x18\x01 \x01(\v2$.angzarr.ProcessManagerHandleRequestR\arequest\x12:\n" +
	"\rpoint_in_time\x18\x02 \x01(\v2\x16.angzarr.TemporalQueryR\vpointInTime\"\x85\x01\n" +
	"\x1cProcessManagerPrepareRequest\x12,\n" +
	"\atrigger\x18\x01 \x01(\v2\x12.angzarr.EventBookR\atrigger\x127\n" +
	"\rprocess_state\x18\x02 \x01(\v2\x12.angzarr.EventBookR\fprocessState\"S\n" +
	"\x1dProcessManagerPrepareResponse\x122\n" +
	"\fdestinations\x18\x01 \x03(\v2\x0e.angzarr.CoverR\fdestinations\"\xbc\x01\n" +
	"\x1bProcessManagerHandleRequest\x12,\n" +
	"\atrigger\x18\x01 \x01(\v2\x12.angzarr.EventBookR\atrigger\x127\n" +
	"\rprocess_state\x18\x02 \x01(\v2\x12.angzarr.EventBookR\fprocessState\x126\n" +
	"\fdestinations\x18\x03 \x03(\v2\x12.angzarr.EventBookR\fdestinations\"\x8b\x01\n" +
	"\x1cProcessManagerHandleResponse\x120\n" +
	"\bcommands\x18\x01 \x03(\v2\x14.angzarr.CommandBookR\bcommands\x129\n" +
	"\x0eprocess_events\x18\x02 \x01(\v2\x12.angzarr.EventBookR\rprocessEvents\"\xb5\x01\n" +
	"\x0eProcessTimeout\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\fprocess_type\x18\x02 \x01(\tR\vprocessType\x12!\n" +
	"\ftimeout_type\x18\x03 \x01(\tR\vtimeoutType\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline2\xc8\x01\n" +
	"\x15ProcessManagerService\x12X\n" +
	"\aPrepare\x12%.angzarr.ProcessManagerPrepareRequest\x1a&.angzarr.ProcessManagerPrepareResponse\x12U\n" +
	"\x06Handle\x12$.angzarr.ProcessManagerHandleRequest\x1a%.angzarr.ProcessManagerHandleResponse2{\n" +
	" ProcessManagerCoordinatorService\x12W\n" +
	"\x11HandleSpeculative\x12\x1b.angzarr.SpeculatePmRequest\x1a%.angzarr.ProcessManagerHandleResponseB\x99\x01\n" +
	"\vcom.angzarrB\x13ProcessManagerProtoP\x01Z9github.com/benjaminabbitt/angzarr/client/go/proto/angzarr\xa2\x02\x03AXX\xaa\x02\aAngzarr\xca\x02\aAngzarr\xe2\x02\x13Angzarr\\GPBMetadata\xea\x02\aAngzarrb\x06proto3"

var (
	file_angzarr_process_manager_proto_rawDescOnce sync.Once
	file_angzarr_process_manager_proto_rawDescData []byte
)

func file_angzarr_process_manager_proto_rawDescGZIP() []byte {
	file_angzarr_process_manager_proto_rawDescOnce.Do(func() {
		file_angzarr_process_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_angzarr_process_manager_proto_rawDesc), len(file_angzarr_process_manager_proto_rawDesc)))
	})
	return file_angzarr_process_manager_proto_rawDescData
}

var file_angzarr_process_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_angzarr_process_manager_proto_goTypes = []any{
	(*SpeculatePmRequest)(nil),            // 0: angzarr.SpeculatePmRequest
	(*ProcessManagerPrepareRequest)(nil),  // 1: angzarr.ProcessManagerPrepareRequest
	(*ProcessManagerPrepareResponse)(nil), // 2: angzarr.ProcessManagerPrepareResponse
	(*ProcessManagerHandleRequest)(nil),   // 3: angzarr.ProcessManagerHandleRequest
	(*ProcessManagerHandleResponse)(nil),  // 4: angzarr.ProcessManagerHandleResponse
	(*ProcessTimeout)(nil),                // 5: angzarr.ProcessTimeout
	(*TemporalQuery)(nil),                 // 6: angzarr.TemporalQuery
	(*EventBook)(nil),                     // 7: angzarr.EventBook
	(*Cover)(nil),                         // 8: angzarr.Cover
	(*CommandBook)(nil),                   // 9: angzarr.CommandBook
	(*timestamppb.Timestamp)(nil),         // 10: google.protobuf.Timestamp
}
var file_angzarr_process_manager_proto_depIdxs = []int32{
	3,  // 0: angzarr.SpeculatePmRequest.request:type_name -> angzarr.ProcessManagerHandleRequest
	6,  // 1: angzarr.SpeculatePmRequest.point_in_time:type_name -> angzarr.TemporalQuery
	7,  // 2: angzarr.ProcessManagerPrepareRequest.trigger:type_name -> angzarr.EventBook
	7,  // 3: angzarr.ProcessManagerPrepareRequest.process_state:type_name -> angzarr.EventBook
	8,  // 4: angzarr.ProcessManagerPrepareResponse.destinations:type_name -> angzarr.Cover
	7,  // 5: angzarr.ProcessManagerHandleRequest.trigger:type_name -> angzarr.EventBook
	7,  // 6: angzarr.ProcessManagerHandleRequest.process_state:type_name -> angzarr.EventBook
	7,  // 7: angzarr.ProcessManagerHandleRequest.destinations:type_name -> angzarr.EventBook
	9,  // 8: angzarr.ProcessManagerHandleResponse.commands:type_name -> angzarr.CommandBook
	7,  // 9: angzarr.ProcessManagerHandleResponse.process_events:type_name -> angzarr.EventBook
	10, // 10: angzarr.ProcessTimeout.deadline:type_name -> google.protobuf.Timestamp
	1,  // 11: angzarr.ProcessManagerService.Prepare:input_type -> angzarr.ProcessManagerPrepareRequest
	3,  // 12: angzarr.ProcessManagerService.Handle:input_type -> angzarr.ProcessManagerHandleRequest
	0,  // 13: angzarr.ProcessManagerCoordinatorService.HandleSpeculative:input_type -> angzarr.SpeculatePmRequest
	2,  // 14: angzarr.ProcessManagerService.Prepare:output_type -> angzarr.ProcessManagerPrepareResponse
	4,  // 15: angzarr.ProcessManagerService.Handle:output_type -> angzarr.ProcessManagerHandleResponse
	4,  // 16: angzarr.ProcessManagerCoordinatorService.HandleSpeculative:output_type -> angzarr.ProcessManagerHandleResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_angzarr_process_manager_proto_init() }
func file_angzarr_process_manager_proto_init() {
	if File_angzarr_process_manager_proto != nil {
		return
	}
	file_angzarr_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_angzarr_process_manager_proto_rawDesc), len(file_angzarr_process_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_angzarr_process_manager_proto_goTypes,
		DependencyIndexes: file_angzarr_process_manager_proto_depIdxs,
		MessageInfos:      file_angzarr_process_manager_proto_msgTypes,
	}.Build()
	File_angzarr_process_manager_proto = out.File
	file_angzarr_process_manager_proto_goTypes = nil
	file_angzarr_process_manager_proto_depIdxs = nil
}
