// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: angzarr/saga.proto

package angzarr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_angzarr_saga_proto protoreflect.FileDescriptor

const file_angzarr_saga_proto_rawDesc = "" +
	"\n" +
	"\x12angzarr/saga.proto\x12\aangzarr\x1a\x13angzarr/types.proto2\xe0\x01\n" +
	"\vSagaService\x12L\n" +
	"\rGetDescriptor\x12\x1d.angzarr.GetDescriptorRequest\x1a\x1c.angzarr.ComponentDescriptor\x12D\n" +
	"\aPrepare\x12\x1b.angzarr.SagaPrepareRequest\x1a\x1c.angzarr.SagaPrepareResponse\x12=\n" +
	"\aExecute\x12\x1b.angzarr.SagaExecuteRequest\x1a\x15.angzarr.SagaResponse2b\n" +
	"\x16SagaCoordinatorService\x12H\n" +
	"\x12ExecuteSpeculative\x12\x1b.angzarr.SagaExecuteRequest\x1a\x15.angzarr.SagaResponseB\x8f\x01\n" +
	"\vcom.angzarrB\tSagaProtoP\x01Z9github.com/benjaminabbitt/angzarr/client/go/proto/angzarr\xa2\x02\x03AXX\xaa\x02\aAngzarr\xca\x02\aAngzarr\xe2\x02\x13Angzarr\\GPBMetadata\xea\x02\aAngzarrb\x06proto3"

var file_angzarr_saga_proto_goTypes = []any{
	(*GetDescriptorRequest)(nil), // 0: angzarr.GetDescriptorRequest
	(*SagaPrepareRequest)(nil),   // 1: angzarr.SagaPrepareRequest
	(*SagaExecuteRequest)(nil),   // 2: angzarr.SagaExecuteRequest
	(*ComponentDescriptor)(nil),  // 3: angzarr.ComponentDescriptor
	(*SagaPrepareResponse)(nil),  // 4: angzarr.SagaPrepareResponse
	(*SagaResponse)(nil),         // 5: angzarr.SagaResponse
}
var file_angzarr_saga_proto_depIdxs = []int32{
	0, // 0: angzarr.SagaService.GetDescriptor:input_type -> angzarr.GetDescriptorRequest
	1, // 1: angzarr.SagaService.Prepare:input_type -> angzarr.SagaPrepareRequest
	2, // 2: angzarr.SagaService.Execute:input_type -> angzarr.SagaExecuteRequest
	2, // 3: angzarr.SagaCoordinatorService.ExecuteSpeculative:input_type -> angzarr.SagaExecuteRequest
	3, // 4: angzarr.SagaService.GetDescriptor:output_type -> angzarr.ComponentDescriptor
	4, // 5: angzarr.SagaService.Prepare:output_type -> angzarr.SagaPrepareResponse
	5, // 6: angzarr.SagaService.Execute:output_type -> angzarr.SagaResponse
	5, // 7: angzarr.SagaCoordinatorService.ExecuteSpeculative:output_type -> angzarr.SagaResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_angzarr_saga_proto_init() }
func file_angzarr_saga_proto_init() {
	if File_angzarr_saga_proto != nil {
		return
	}
	file_angzarr_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_angzarr_saga_proto_rawDesc), len(file_angzarr_saga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_angzarr_saga_proto_goTypes,
		DependencyIndexes: file_angzarr_saga_proto_depIdxs,
	}.Build()
	File_angzarr_saga_proto = out.File
	file_angzarr_saga_proto_goTypes = nil
	file_angzarr_saga_proto_depIdxs = nil
}
