// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: angzarr/upcaster.proto

package angzarr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpcasterService_Upcast_FullMethodName = "/angzarr.UpcasterService/Upcast"
)

// UpcasterServiceClient is the client API for UpcasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UpcasterService: transforms old event versions to current versions
// Deployed as optional sidecar container in aggregate pod
type UpcasterServiceClient interface {
	// Transform events to current version
	// Returns events in same order, transformed where applicable
	Upcast(ctx context.Context, in *UpcastRequest, opts ...grpc.CallOption) (*UpcastResponse, error)
}

type upcasterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpcasterServiceClient(cc grpc.ClientConnInterface) UpcasterServiceClient {
	return &upcasterServiceClient{cc}
}

func (c *upcasterServiceClient) Upcast(ctx context.Context, in *UpcastRequest, opts ...grpc.CallOption) (*UpcastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpcastResponse)
	err := c.cc.Invoke(ctx, UpcasterService_Upcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpcasterServiceServer is the server API for UpcasterService service.
// All implementations must embed UnimplementedUpcasterServiceServer
// for forward compatibility.
//
// UpcasterService: transforms old event versions to current versions
// Deployed as optional sidecar container in aggregate pod
type UpcasterServiceServer interface {
	// Transform events to current version
	// Returns events in same order, transformed where applicable
	Upcast(context.Context, *UpcastRequest) (*UpcastResponse, error)
	mustEmbedUnimplementedUpcasterServiceServer()
}

// UnimplementedUpcasterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpcasterServiceServer struct{}

func (UnimplementedUpcasterServiceServer) Upcast(context.Context, *UpcastRequest) (*UpcastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Upcast not implemented")
}
func (UnimplementedUpcasterServiceServer) mustEmbedUnimplementedUpcasterServiceServer() {}
func (UnimplementedUpcasterServiceServer) testEmbeddedByValue()                         {}

// UnsafeUpcasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpcasterServiceServer will
// result in compilation errors.
type UnsafeUpcasterServiceServer interface {
	mustEmbedUnimplementedUpcasterServiceServer()
}

func RegisterUpcasterServiceServer(s grpc.ServiceRegistrar, srv UpcasterServiceServer) {
	// If the following call panics, it indicates UnimplementedUpcasterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpcasterService_ServiceDesc, srv)
}

func _UpcasterService_Upcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpcasterServiceServer).Upcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpcasterService_Upcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpcasterServiceServer).Upcast(ctx, req.(*UpcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpcasterService_ServiceDesc is the grpc.ServiceDesc for UpcasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpcasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "angzarr.UpcasterService",
	HandlerType: (*UpcasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upcast",
			Handler:    _UpcasterService_Upcast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "angzarr/upcaster.proto",
}
