// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: angzarr/upcaster.proto

package angzarr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Events        []*EventPage           `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpcastRequest) Reset() {
	*x = UpcastRequest{}
	mi := &file_angzarr_upcaster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcastRequest) ProtoMessage() {}

func (x *UpcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_upcaster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcastRequest.ProtoReflect.Descriptor instead.
func (*UpcastRequest) Descriptor() ([]byte, []int) {
	return file_angzarr_upcaster_proto_rawDescGZIP(), []int{0}
}

func (x *UpcastRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UpcastRequest) GetEvents() []*EventPage {
	if x != nil {
		return x.Events
	}
	return nil
}

type UpcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventPage           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpcastResponse) Reset() {
	*x = UpcastResponse{}
	mi := &file_angzarr_upcaster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcastResponse) ProtoMessage() {}

func (x *UpcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_angzarr_upcaster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcastResponse.ProtoReflect.Descriptor instead.
func (*UpcastResponse) Descriptor() ([]byte, []int) {
	return file_angzarr_upcaster_proto_rawDescGZIP(), []int{1}
}

func (x *UpcastResponse) GetEvents() []*EventPage {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_angzarr_upcaster_proto protoreflect.FileDescriptor

const file_angzarr_upcaster_proto_rawDesc = "" +
	"\n" +
	"\x16angzarr/upcaster.proto\x12\aangzarr\x1a\x13angzarr/types.proto\"S\n" +
	"\rUpcastRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12*\n" +
	"\x06events\x18\x02 \x03(\v2\x12.angzarr.EventPageR\x06events\"<\n" +
	"\x0eUpcastResponse\x12*\n" +
	"\x06events\x18\x01 \x03(\v2\x12.angzarr.EventPageR\x06events2L\n" +
	"\x0fUpcasterService\x129\n" +
	"\x06Upcast\x12\x16.angzarr.UpcastRequest\x1a\x17.angzarr.UpcastResponseB\x93\x01\n" +
	"\vcom.angzarrB\rUpcasterProtoP\x01Z9github.com/benjaminabbitt/angzarr/client/go/proto/angzarr\xa2\x02\x03AXX\xaa\x02\aAngzarr\xca\x02\aAngzarr\xe2\x02\x13Angzarr\\GPBMetadata\xea\x02\aAngzarrb\x06proto3"

var (
	file_angzarr_upcaster_proto_rawDescOnce sync.Once
	file_angzarr_upcaster_proto_rawDescData []byte
)

func file_angzarr_upcaster_proto_rawDescGZIP() []byte {
	file_angzarr_upcaster_proto_rawDescOnce.Do(func() {
		file_angzarr_upcaster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_angzarr_upcaster_proto_rawDesc), len(file_angzarr_upcaster_proto_rawDesc)))
	})
	return file_angzarr_upcaster_proto_rawDescData
}

var file_angzarr_upcaster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_angzarr_upcaster_proto_goTypes = []any{
	(*UpcastRequest)(nil),  // 0: angzarr.UpcastRequest
	(*UpcastResponse)(nil), // 1: angzarr.UpcastResponse
	(*EventPage)(nil),      // 2: angzarr.EventPage
}
var file_angzarr_upcaster_proto_depIdxs = []int32{
	2, // 0: angzarr.UpcastRequest.events:type_name -> angzarr.EventPage
	2, // 1: angzarr.UpcastResponse.events:type_name -> angzarr.EventPage
	0, // 2: angzarr.UpcasterService.Upcast:input_type -> angzarr.UpcastRequest
	1, // 3: angzarr.UpcasterService.Upcast:output_type -> angzarr.UpcastResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_angzarr_upcaster_proto_init() }
func file_angzarr_upcaster_proto_init() {
	if File_angzarr_upcaster_proto != nil {
		return
	}
	file_angzarr_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_angzarr_upcaster_proto_rawDesc), len(file_angzarr_upcaster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_angzarr_upcaster_proto_goTypes,
		DependencyIndexes: file_angzarr_upcaster_proto_depIdxs,
		MessageInfos:      file_angzarr_upcaster_proto_msgTypes,
	}.Build()
	File_angzarr_upcaster_proto = out.File
	file_angzarr_upcaster_proto_goTypes = nil
	file_angzarr_upcaster_proto_depIdxs = nil
}
