apiVersion: v1
kind: Service
metadata:
  name: {{ include "angzarr-db-redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "angzarr-db-redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "angzarr-db-redis.selectorLabels" . | nindent 4 }}
---
# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: {{ include "angzarr-db-redis.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "angzarr-db-redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "angzarr-db-redis.selectorLabels" . | nindent 4 }}
