# Inventory Business Logic - Java

set shell := ["bash", "-c"]

TOP := `git rev-parse --show-toplevel`

default:
    @just --list

build:
    mvn compile -q

run:
    mvn exec:java -Dexec.mainClass=dev.angzarr.examples.inventory.InventoryServer

clean:
    mvn clean -q

proto:
    mvn generate-sources -q

jar:
    mvn package -DskipTests -q

copy-features:
    rm -rf src/test/resources/features
    mkdir -p src/test/resources
    cp -r {{TOP}}/examples/features src/test/resources/

unit:
    mvn test -Dtest=*Test -DfailIfNoTests=false

acceptance: copy-features
    ANGZARR_TEST_MODE=container mvn test -Dtest=*IT -DfailIfNoTests=false

test: unit acceptance

test-unit: unit
