{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "angzarr-db-postgres.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "angzarr-db-postgres.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.database.owner | quote }}
  password: {{ required "auth.password is required (or use auth.existingSecret)" .Values.auth.password | quote }}
{{- end }}
