# Business Logic - Ruby

set shell := ["bash", "-c"]

TOP := `git rev-parse --show-toplevel`

default:
    @just --list

install:
    bundle install

build: install

run: install
    bundle exec ruby server.rb

clean:
    rm -rf .bundle vendor

copy-features:
    rm -rf features
    cp -r {{TOP}}/examples/features .

unit: install
    bundle exec rspec spec/

acceptance: install copy-features
    ANGZARR_TEST_MODE=container bundle exec cucumber features/

test: unit acceptance

test-unit: unit
