# RabbitMQ credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq-simple.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq-simple.labels" . | nindent 4 }}
type: Opaque
data:
  rabbitmq-password: {{ .Values.auth.password | b64enc | quote }}
