FROM mcr.microsoft.com/devcontainers/java:17

# Install just
RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

# Install protoc
RUN apt-get update && apt-get install -y protobuf-compiler

# Mark as devcontainer for justfile detection
ENV DEVCONTAINER=true
