apiVersion: v1
kind: Service
metadata:
  name: {{ include "angzarr-pm.fullname" . }}
  labels:
    {{- include "angzarr-pm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: coordinator
      protocol: TCP
      name: grpc
  selector:
    {{- include "angzarr-pm.selectorLabels" . | nindent 4 }}
