# Gemfile for cucumber-cpp wire protocol testing
# Pin versions that are known to work with cucumber-cpp 0.7.x

source 'https://rubygems.org'

gem 'cucumber', '~> 3.1.2'
gem 'cucumber-wire', '~> 0.0.1'
