# Common Go utilities

set shell := ["bash", "-c"]

TOP := `git rev-parse --show-toplevel`

# Show available commands
default:
    @just --list

# Copy generated proto files
proto:
    mkdir -p proto/examples
    cp -r "{{TOP}}/generated/go/examples/"* proto/examples/ 2>/dev/null || true

# Build
build: proto
    go mod tidy
    go build ./...

# Clean
clean:
    rm -rf proto/examples/*.go
