# Business Logic - C++

set shell := ["bash", "-c"]

TOP := `git rev-parse --show-toplevel`

default:
    @just --list

configure:
    cmake -B build -S .

build: configure
    cmake --build build

run: build
    ./build/server

clean:
    rm -rf build

copy-features:
    rm -rf features
    cp -r {{TOP}}/examples/features .

unit: build
    ./build/tests || echo "No tests found"

acceptance: build copy-features
    ANGZARR_TEST_MODE=container ./build/acceptance_tests || echo "No acceptance tests found"

test: unit acceptance

test-unit: unit
