// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Angzarr.Client.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class EventDecoding_PayloadDeserializationFeature : object, Xunit.IClassFixture<EventDecoding_PayloadDeserializationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "event_decoding.feature"
#line hidden
        
        public EventDecoding_PayloadDeserializationFeature(EventDecoding_PayloadDeserializationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "../../features", "Event Decoding - Payload Deserialization", "  Events are stored as google.protobuf.Any with type_url and value.\n  Decoding ex" +
                    "tracts typed messages from the Any wrapper based on\n  type_url matching. This is" +
                    " fundamental for state building and projections.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Decode event with matching type URL")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Decode event with matching type URL")]
        public async System.Threading.Tasks.Task DecodeEventWithMatchingTypeURL()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Decode event with matching type URL", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
    await testRunner.GivenAsync("an event with type_url \"type.googleapis.com/orders.OrderCreated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
    await testRunner.AndAsync("valid protobuf bytes for OrderCreated", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
    await testRunner.WhenAsync("I decode the event as OrderCreated", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
    await testRunner.ThenAsync("decoding should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
    await testRunner.AndAsync("I should get an OrderCreated message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Decode event with type URL suffix match")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Decode event with type URL suffix match")]
        public async System.Threading.Tasks.Task DecodeEventWithTypeURLSuffixMatch()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Decode event with type URL suffix match", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
    await testRunner.GivenAsync("an event with type_url \"type.googleapis.com/orders.OrderCreated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
    await testRunner.WhenAsync("I decode looking for suffix \"OrderCreated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
    await testRunner.ThenAsync("decoding should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
    await testRunner.AndAsync("the full type_url prefix should be ignored", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Decode returns None for type mismatch")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Decode returns None for type mismatch")]
        public async System.Threading.Tasks.Task DecodeReturnsNoneForTypeMismatch()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Decode returns None for type mismatch", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.GivenAsync("an event with type_url \"type.googleapis.com/orders.ItemAdded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
    await testRunner.WhenAsync("I decode the event as OrderCreated", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.ThenAsync("decoding should return None/null", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 27
    await testRunner.AndAsync("no error should be raised", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="EventPage contains sequence")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "EventPage contains sequence")]
        public async System.Threading.Tasks.Task EventPageContainsSequence()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("EventPage contains sequence", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("an EventPage at sequence 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
    await testRunner.ThenAsync("event.sequence should be 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="EventPage contains created_at timestamp")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "EventPage contains created_at timestamp")]
        public async System.Threading.Tasks.Task EventPageContainsCreated_AtTimestamp()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("EventPage contains created_at timestamp", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
    await testRunner.GivenAsync("an EventPage with timestamp", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
    await testRunner.ThenAsync("event.created_at should be a valid timestamp", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 40
    await testRunner.AndAsync("the timestamp should be parseable", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="EventPage payload is Event variant")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "EventPage payload is Event variant")]
        public async System.Threading.Tasks.Task EventPagePayloadIsEventVariant()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("EventPage payload is Event variant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
    await testRunner.GivenAsync("an EventPage with Event payload", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
    await testRunner.ThenAsync("event.payload should be Event variant", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 45
    await testRunner.AndAsync("the Event should contain the Any wrapper", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="EventPage payload can be PayloadReference")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "EventPage payload can be PayloadReference")]
        public async System.Threading.Tasks.Task EventPagePayloadCanBePayloadReference()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("EventPage payload can be PayloadReference", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
    await testRunner.GivenAsync("an EventPage with offloaded payload", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 49
    await testRunner.ThenAsync("event.payload should be PayloadReference variant", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
    await testRunner.AndAsync("the reference should contain storage details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Full type URL matching")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Full type URL matching")]
        public async System.Threading.Tasks.Task FullTypeURLMatching()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Full type URL matching", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
    await testRunner.GivenAsync("an event with type_url \"type.googleapis.com/myapp.events.v1.OrderCreated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 58
    await testRunner.WhenAsync("I match against \"type.googleapis.com/myapp.events.v1.OrderCreated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
    await testRunner.ThenAsync("the match should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Suffix matching for convenience")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Suffix matching for convenience")]
        public async System.Threading.Tasks.Task SuffixMatchingForConvenience()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Suffix matching for convenience", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 62
    await testRunner.GivenAsync("an event with type_url \"type.googleapis.com/myapp.events.v1.OrderCreated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
    await testRunner.WhenAsync("I match against suffix \"OrderCreated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
    await testRunner.ThenAsync("the match should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Suffix matching is case-sensitive")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Suffix matching is case-sensitive")]
        public async System.Threading.Tasks.Task SuffixMatchingIsCase_Sensitive()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Suffix matching is case-sensitive", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 67
    await testRunner.GivenAsync("an event with type_url ending in \"OrderCreated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
    await testRunner.WhenAsync("I match against suffix \"ordercreated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
    await testRunner.ThenAsync("the match should fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Versioned type URLs")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Versioned type URLs")]
        public async System.Threading.Tasks.Task VersionedTypeURLs()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Versioned type URLs", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "type.googleapis.com/myapp.events.v1.OrderCreated"});
                table9.AddRow(new string[] {
                            "type.googleapis.com/myapp.events.v2.OrderCreated"});
#line 72
    await testRunner.GivenAsync("events with type_urls:", ((string)(null)), table9, "Given ");
#line hidden
#line 75
    await testRunner.WhenAsync("I match against \"v1.OrderCreated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 76
    await testRunner.ThenAsync("only the v1 event should match", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Payload bytes are valid protobuf")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Payload bytes are valid protobuf")]
        public async System.Threading.Tasks.Task PayloadBytesAreValidProtobuf()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Payload bytes are valid protobuf", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 83
    await testRunner.GivenAsync("an event with properly encoded payload", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 84
    await testRunner.WhenAsync("I decode the payload bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 85
    await testRunner.ThenAsync("the protobuf message should deserialize correctly", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 86
    await testRunner.AndAsync("all fields should be populated", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Empty payload bytes")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Empty payload bytes")]
        public async System.Threading.Tasks.Task EmptyPayloadBytes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Empty payload bytes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 88
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 89
    await testRunner.GivenAsync("an event with empty payload bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 90
    await testRunner.WhenAsync("I decode the payload", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 91
    await testRunner.ThenAsync("the message should have default values", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 92
    await testRunner.AndAsync("no error should occur (empty protobuf is valid)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Corrupted payload bytes")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Corrupted payload bytes")]
        public async System.Threading.Tasks.Task CorruptedPayloadBytes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Corrupted payload bytes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 94
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 95
    await testRunner.GivenAsync("an event with corrupted payload bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 96
    await testRunner.WhenAsync("I attempt to decode", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 97
    await testRunner.ThenAsync("decoding should fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 98
    await testRunner.AndAsync("an error should indicate deserialization failure", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="EventPage with no payload")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "EventPage with no payload")]
        public async System.Threading.Tasks.Task EventPageWithNoPayload()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("EventPage with no payload", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 104
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 105
    await testRunner.GivenAsync("an EventPage with payload = None", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 106
    await testRunner.WhenAsync("I attempt to decode", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
    await testRunner.ThenAsync("decoding should return None/null", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 108
    await testRunner.AndAsync("no crash should occur", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Event with no value bytes")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Event with no value bytes")]
        public async System.Threading.Tasks.Task EventWithNoValueBytes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Event with no value bytes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 110
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 111
    await testRunner.GivenAsync("an Event Any with empty value", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 112
    await testRunner.WhenAsync("I decode", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 113
    await testRunner.ThenAsync("the result should be a default message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 114
    await testRunner.AndAsync("no error should occur", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="decode_event helper function")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "decode_event helper function")]
        public async System.Threading.Tasks.Task Decode_EventHelperFunction()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("decode_event helper function", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 120
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 121
    await testRunner.GivenAsync("the decode_event<T>(event, type_suffix) function", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 122
    await testRunner.WhenAsync("I call decode_event(event, \"OrderCreated\")", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 123
    await testRunner.ThenAsync("if type matches, Some(T) is returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 124
    await testRunner.AndAsync("if type doesn\'t match, None is returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="events_from_response helper")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "events_from_response helper")]
        public async System.Threading.Tasks.Task Events_From_ResponseHelper()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("events_from_response helper", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 126
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 127
    await testRunner.GivenAsync("a CommandResponse with events", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 128
    await testRunner.WhenAsync("I call events_from_response(response)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 129
    await testRunner.ThenAsync("I should get a slice/list of EventPages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="events_from_response with no events")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "events_from_response with no events")]
        public async System.Threading.Tasks.Task Events_From_ResponseWithNoEvents()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("events_from_response with no events", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 131
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 132
    await testRunner.GivenAsync("a CommandResponse with no events", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 133
    await testRunner.WhenAsync("I call events_from_response(response)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 134
    await testRunner.ThenAsync("I should get an empty slice/list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Decode multiple events of same type")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Decode multiple events of same type")]
        public async System.Threading.Tasks.Task DecodeMultipleEventsOfSameType()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Decode multiple events of same type", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 140
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 141
    await testRunner.GivenAsync("5 events all of type \"ItemAdded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 142
    await testRunner.WhenAsync("I decode each as ItemAdded", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 143
    await testRunner.ThenAsync("all 5 should decode successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 144
    await testRunner.AndAsync("each should have correct data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Decode mixed event types")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Decode mixed event types")]
        public async System.Threading.Tasks.Task DecodeMixedEventTypes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Decode mixed event types", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 146
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 147
    await testRunner.GivenAsync("events: OrderCreated, ItemAdded, ItemAdded, OrderShipped", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 148
    await testRunner.WhenAsync("I decode by type", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 149
    await testRunner.ThenAsync("OrderCreated should decode as OrderCreated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 150
    await testRunner.AndAsync("ItemAdded events should decode as ItemAdded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 151
    await testRunner.AndAsync("OrderShipped should decode as OrderShipped", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filter events by type")]
        [Xunit.TraitAttribute("FeatureTitle", "Event Decoding - Payload Deserialization")]
        [Xunit.TraitAttribute("Description", "Filter events by type")]
        public async System.Threading.Tasks.Task FilterEventsByType()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filter events by type", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 153
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 154
    await testRunner.GivenAsync("events: OrderCreated, ItemAdded, ItemAdded, OrderShipped", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 155
    await testRunner.WhenAsync("I filter for \"ItemAdded\" events", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 156
    await testRunner.ThenAsync("I should get 2 events", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 157
    await testRunner.AndAsync("both should be ItemAdded type", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await EventDecoding_PayloadDeserializationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await EventDecoding_PayloadDeserializationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
