apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: poker-go

# Requires base angzarr infrastructure
requires:
  - path: ../../skaffold.yaml

build:
  tagPolicy:
    gitCommit:
      prefix: "dev-"
      variant: AbbrevCommitSha
  local:
    push: true
    useBuildkit: false
    concurrency: 1
  artifacts:
    - image: ghcr.io/angzarr-io/poker-go-player
      context: ../..
      docker:
        dockerfile: examples/go/Containerfile
        target: agg-player

    - image: ghcr.io/angzarr-io/poker-go-table
      context: ../..
      docker:
        dockerfile: examples/go/Containerfile
        target: agg-table

    - image: ghcr.io/angzarr-io/poker-go-hand
      context: ../..
      docker:
        dockerfile: examples/go/Containerfile
        target: agg-hand

deploy:
  helm:
    releases:
      - name: poker-go
        chartPath: ../../deploy/helm/angzarr
        namespace: angzarr
        createNamespace: true
        valuesFiles:
          - values.yaml
        setValues:
          # Player aggregate
          applications.business[0].name: poker-player
          applications.business[0].image.repository: ghcr.io/angzarr-io/poker-go-player
          applications.business[0].image.tag: latest
          applications.business[0].domain: player
          applications.business[0].port: 50201
          # Table aggregate
          applications.business[1].name: poker-table
          applications.business[1].image.repository: ghcr.io/angzarr-io/poker-go-table
          applications.business[1].image.tag: latest
          applications.business[1].domain: table
          applications.business[1].port: 50202
          # Hand aggregate
          applications.business[2].name: poker-hand
          applications.business[2].image.repository: ghcr.io/angzarr-io/poker-go-hand
          applications.business[2].image.tag: latest
          applications.business[2].domain: hand
          applications.business[2].port: 50203
