apiVersion: v1
kind: Service
metadata:
  name: {{ include "angzarr-domain.fullname" . }}
  labels:
    {{- include "angzarr-domain.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: coordinator
      protocol: TCP
      name: grpc
    {{- if .Values.grpcGateway.enabled }}
    - port: {{ .Values.grpcGateway.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.grpcGateway.nodePort }}
      nodePort: {{ .Values.grpcGateway.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "angzarr-domain.selectorLabels" . | nindent 4 }}
