# Common Rust utilities

set shell := ["bash", "-c"]

TOP := `git rev-parse --show-toplevel`

# Show available commands
default:
    @just --list

# Copy generated proto files
proto:
    mkdir -p src/proto
    cp "{{TOP}}/generated/rust/examples/examples.rs" src/proto/examples.rs

# Build
build: proto
    cargo build

# Clean
clean:
    cargo clean
