{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "angzarr-mq-rabbitmq.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "angzarr-mq-rabbitmq.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ required "auth.password is required (or use auth.existingSecret)" .Values.auth.password | quote }}
{{- end }}
