apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: angzarr-rust-examples

# Require framework images - provides IMAGE_TAG_* template variables for deploy
requires:
  - path: ../../skaffold.yaml
    configs: [angzarr-build]

build:
  tagPolicy:
    sha256: {}
  local:
    push: true
    useBuildkit: false
    concurrency: 0
  artifacts:
    # Domain Aggregates
    - image: localhost:5001/aggregate-order-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: order-dev

    - image: localhost:5001/aggregate-inventory-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: inventory-dev

    - image: localhost:5001/aggregate-fulfillment-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: fulfillment-dev

    # Sagas
    - image: localhost:5001/saga-order-fulfillment-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: saga-order-fulfillment-dev

    - image: localhost:5001/saga-order-inventory-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: saga-order-inventory-dev

    - image: localhost:5001/saga-fulfillment-inventory-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: saga-fulfillment-inventory-dev

    # Process Managers
    - image: localhost:5001/process-manager-fulfillment-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: process-manager-fulfillment-dev

    # Projectors
    - image: localhost:5001/projector-inventory-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: projector-inventory-dev

deploy:
  helm:
    releases:
      - name: angzarr
        chartPath: ../../deploy/helm/angzarr
        namespace: angzarr
        createNamespace: true
        valuesFiles:
          - ../../deploy/helm/angzarr/values-rust.yaml
        setValueTemplates:
          # Framework sidecar images
          images.aggregate.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_aggregate}}"
          images.aggregate.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_aggregate}}"
          images.projector.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_projector}}"
          images.projector.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_projector}}"
          images.saga.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_saga}}"
          images.saga.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_saga}}"
          images.processManager.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_process_manager}}"
          images.processManager.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_process_manager}}"
          images.gateway.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_gateway}}"
          images.gateway.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_gateway}}"
          # Business aggregate images
          applications.business[0].image.repository: "{{.IMAGE_REPO_localhost_5001_aggregate_order_rs}}"
          applications.business[0].image.tag: "{{.IMAGE_TAG_localhost_5001_aggregate_order_rs}}"
          applications.business[1].image.repository: "{{.IMAGE_REPO_localhost_5001_aggregate_inventory_rs}}"
          applications.business[1].image.tag: "{{.IMAGE_TAG_localhost_5001_aggregate_inventory_rs}}"
          applications.business[2].image.repository: "{{.IMAGE_REPO_localhost_5001_aggregate_fulfillment_rs}}"
          applications.business[2].image.tag: "{{.IMAGE_TAG_localhost_5001_aggregate_fulfillment_rs}}"
          # Saga images
          applications.sagas[0].image.repository: "{{.IMAGE_REPO_localhost_5001_saga_order_fulfillment_rs}}"
          applications.sagas[0].image.tag: "{{.IMAGE_TAG_localhost_5001_saga_order_fulfillment_rs}}"
          applications.sagas[1].image.repository: "{{.IMAGE_REPO_localhost_5001_saga_order_inventory_rs}}"
          applications.sagas[1].image.tag: "{{.IMAGE_TAG_localhost_5001_saga_order_inventory_rs}}"
          applications.sagas[2].image.repository: "{{.IMAGE_REPO_localhost_5001_saga_fulfillment_inventory_rs}}"
          applications.sagas[2].image.tag: "{{.IMAGE_TAG_localhost_5001_saga_fulfillment_inventory_rs}}"
          # Process Manager images
          applications.processManagers[0].image.repository: "{{.IMAGE_REPO_localhost_5001_process_manager_fulfillment_rs}}"
          applications.processManagers[0].image.tag: "{{.IMAGE_TAG_localhost_5001_process_manager_fulfillment_rs}}"
          # Projector images
          applications.projectors[0].image.repository: "{{.IMAGE_REPO_localhost_5001_projector_inventory_rs}}"
          applications.projectors[0].image.tag: "{{.IMAGE_TAG_localhost_5001_projector_inventory_rs}}"

profiles:
  # Release profile - musl builds, minimal images
  - name: release
    build:
      artifacts:
        - image: localhost:5001/aggregate-order-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: order

        - image: localhost:5001/aggregate-inventory-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: inventory

        - image: localhost:5001/aggregate-fulfillment-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: fulfillment

        - image: localhost:5001/saga-order-fulfillment-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: saga-order-fulfillment

        - image: localhost:5001/saga-order-inventory-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: saga-order-inventory

        - image: localhost:5001/saga-fulfillment-inventory-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: saga-fulfillment-inventory

        - image: localhost:5001/process-manager-fulfillment-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: process-manager-fulfillment

        - image: localhost:5001/projector-inventory-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: projector-inventory
