apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: angzarr-rust-examples

requires:
  # Require base angzarr config for infrastructure images (build only, not deploy)
  - path: ../../skaffold.yaml
    configs: [angzarr-build]

build:
  local:
    push: true
    useBuildkit: false
  artifacts:
    # Rust example services
    - image: localhost:5001/entity-customer-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: customer

    - image: localhost:5001/entity-transaction-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: transaction

    - image: localhost:5001/saga-loyalty-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: saga-loyalty

    - image: localhost:5001/projector-receipt-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: projector-receipt

    - image: localhost:5001/projector-log-customer-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: projector-log-customer

    - image: localhost:5001/projector-log-transaction-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: projector-log-transaction

deploy:
  helm:
    releases:
      - name: angzarr
        chartPath: ../../deploy/helm/angzarr
        namespace: angzarr
        createNamespace: true
        valuesFiles:
          - ../../deploy/helm/angzarr/values-rust.yaml

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local:
        push: true

  - name: debug
    build:
      artifacts:
        - image: localhost:5001/entity-customer-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile.dev
            target: customer
