apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: angzarr-rust-examples

# IMPORTANT: All image builds MUST go through skaffold.
# Do NOT manually build with podman/docker and helm upgrade.
# Kind nodes cache images by tag - skaffold uses unique git SHA tags to avoid this.

# Require framework images - provides IMAGE_TAG_* template variables for deploy
requires:
  - path: ../../skaffold.yaml
    configs: [angzarr-build]

build:
  # Use git commit SHA for tags - ensures unique tag per build, avoiding
  # Kind node image cache collisions. Never use sha256 or latest tags.
  tagPolicy:
    gitCommit:
      prefix: "dev-"
      variant: AbbrevCommitSha
  local:
    push: true
    useBuildkit: false
    concurrency: 0
  artifacts:
    # Domain Aggregates
    - image: localhost:5001/agg-order-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: agg-order-dev

    - image: localhost:5001/agg-inventory-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: agg-inventory-dev

    - image: localhost:5001/agg-fulfillment-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: agg-fulfillment-dev

    # Sagas
    - image: localhost:5001/sag-order-fulfillment-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: sag-order-fulfillment-dev

    - image: localhost:5001/sag-order-inventory-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: sag-order-inventory-dev

    - image: localhost:5001/sag-fulfillment-inventory-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: sag-fulfillment-inventory-dev

    # Process Managers
    - image: localhost:5001/pmg-fulfillment-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: pmg-fulfillment-dev

    # Projectors
    - image: localhost:5001/prj-inventory-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: prj-inventory-dev

    # Mock Services (external service integration demos)
    - image: localhost:5001/mock-fraud-service
      context: ../..
      docker:
        dockerfile: examples/rust/mock-fraud-service/Containerfile
        target: runtime

deploy:
  helm:
    releases:
      - name: angzarr
        chartPath: ../../deploy/helm/angzarr
        namespace: angzarr
        createNamespace: true
        valuesFiles:
          - ../../deploy/helm/angzarr/values-rust.yaml
        setValueTemplates:
          # Framework sidecar images
          images.aggregate.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_aggregate}}"
          images.aggregate.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_aggregate}}"
          images.projector.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_projector}}"
          images.projector.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_projector}}"
          images.saga.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_saga}}"
          images.saga.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_saga}}"
          images.processManager.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_process_manager}}"
          images.processManager.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_process_manager}}"
          images.gateway.repository: "{{.IMAGE_REPO_localhost_5001_angzarr_gateway}}"
          images.gateway.tag: "{{.IMAGE_TAG_localhost_5001_angzarr_gateway}}"
          # Business aggregate images
          applications.business[0].image.repository: "{{.IMAGE_REPO_localhost_5001_agg_order_rs}}"
          applications.business[0].image.tag: "{{.IMAGE_TAG_localhost_5001_agg_order_rs}}"
          applications.business[1].image.repository: "{{.IMAGE_REPO_localhost_5001_agg_inventory_rs}}"
          applications.business[1].image.tag: "{{.IMAGE_TAG_localhost_5001_agg_inventory_rs}}"
          applications.business[2].image.repository: "{{.IMAGE_REPO_localhost_5001_agg_fulfillment_rs}}"
          applications.business[2].image.tag: "{{.IMAGE_TAG_localhost_5001_agg_fulfillment_rs}}"
          # Saga images
          applications.sagas[0].image.repository: "{{.IMAGE_REPO_localhost_5001_sag_order_fulfillment_rs}}"
          applications.sagas[0].image.tag: "{{.IMAGE_TAG_localhost_5001_sag_order_fulfillment_rs}}"
          applications.sagas[1].image.repository: "{{.IMAGE_REPO_localhost_5001_sag_order_inventory_rs}}"
          applications.sagas[1].image.tag: "{{.IMAGE_TAG_localhost_5001_sag_order_inventory_rs}}"
          applications.sagas[2].image.repository: "{{.IMAGE_REPO_localhost_5001_sag_fulfillment_inventory_rs}}"
          applications.sagas[2].image.tag: "{{.IMAGE_TAG_localhost_5001_sag_fulfillment_inventory_rs}}"
          # Process Manager images
          applications.processManagers[0].image.repository: "{{.IMAGE_REPO_localhost_5001_pmg_fulfillment_rs}}"
          applications.processManagers[0].image.tag: "{{.IMAGE_TAG_localhost_5001_pmg_fulfillment_rs}}"
          # Projector images
          applications.projectors[0].image.repository: "{{.IMAGE_REPO_localhost_5001_prj_inventory_rs}}"
          applications.projectors[0].image.tag: "{{.IMAGE_TAG_localhost_5001_prj_inventory_rs}}"
          # Mock service images
          mockServices.fraud.image.repository: "{{.IMAGE_REPO_localhost_5001_mock_fraud_service}}"
          mockServices.fraud.image.tag: "{{.IMAGE_TAG_localhost_5001_mock_fraud_service}}"

profiles:
  # Release profile - musl builds, minimal images
  - name: release
    build:
      artifacts:
        - image: localhost:5001/agg-order-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: agg-order

        - image: localhost:5001/agg-inventory-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: agg-inventory

        - image: localhost:5001/agg-fulfillment-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: agg-fulfillment

        - image: localhost:5001/sag-order-fulfillment-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: sag-order-fulfillment

        - image: localhost:5001/sag-order-inventory-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: sag-order-inventory

        - image: localhost:5001/sag-fulfillment-inventory-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: sag-fulfillment-inventory

        - image: localhost:5001/pmg-fulfillment-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: pmg-fulfillment

        - image: localhost:5001/prj-inventory-rs
          context: ../..
          docker:
            dockerfile: examples/rust/Containerfile
            target: prj-inventory
