apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: angzarr-rust-examples

requires:
  # Require base angzarr config for infrastructure images (build only, not deploy)
  - path: ../../skaffold.yaml
    configs: [angzarr-build]

build:
  local:
    push: true
    useBuildkit: false
  artifacts:
    # Domain Aggregates
    - image: localhost:5001/entity-customer-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: customer

    - image: localhost:5001/entity-product-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: product

    - image: localhost:5001/entity-inventory-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: inventory

    - image: localhost:5001/entity-order-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: order

    - image: localhost:5001/entity-cart-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: cart

    - image: localhost:5001/entity-fulfillment-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: fulfillment

    # Sagas
    - image: localhost:5001/saga-loyalty-earn-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: saga-loyalty-earn

    - image: localhost:5001/saga-fulfillment-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: saga-fulfillment

    - image: localhost:5001/saga-cancellation-rs
      context: ../..
      docker:
        dockerfile: examples/rust/Containerfile
        target: saga-cancellation

deploy:
  helm:
    releases:
      - name: angzarr
        chartPath: ../../deploy/helm/angzarr
        namespace: angzarr
        createNamespace: true
        valuesFiles:
          - ../../deploy/helm/angzarr/values-rust.yaml
        setValueTemplates:
          # Business entity images
          applications.business[0].image.repository: "{{.IMAGE_REPO_localhost_5001_entity_customer_rs}}"
          applications.business[0].image.tag: "{{.IMAGE_TAG_localhost_5001_entity_customer_rs}}"
          applications.business[1].image.repository: "{{.IMAGE_REPO_localhost_5001_entity_product_rs}}"
          applications.business[1].image.tag: "{{.IMAGE_TAG_localhost_5001_entity_product_rs}}"
          applications.business[2].image.repository: "{{.IMAGE_REPO_localhost_5001_entity_inventory_rs}}"
          applications.business[2].image.tag: "{{.IMAGE_TAG_localhost_5001_entity_inventory_rs}}"
          applications.business[3].image.repository: "{{.IMAGE_REPO_localhost_5001_entity_order_rs}}"
          applications.business[3].image.tag: "{{.IMAGE_TAG_localhost_5001_entity_order_rs}}"
          applications.business[4].image.repository: "{{.IMAGE_REPO_localhost_5001_entity_cart_rs}}"
          applications.business[4].image.tag: "{{.IMAGE_TAG_localhost_5001_entity_cart_rs}}"
          applications.business[5].image.repository: "{{.IMAGE_REPO_localhost_5001_entity_fulfillment_rs}}"
          applications.business[5].image.tag: "{{.IMAGE_TAG_localhost_5001_entity_fulfillment_rs}}"
          # Saga images
          applications.sagas[0].image.repository: "{{.IMAGE_REPO_localhost_5001_saga_loyalty_earn_rs}}"
          applications.sagas[0].image.tag: "{{.IMAGE_TAG_localhost_5001_saga_loyalty_earn_rs}}"
          applications.sagas[1].image.repository: "{{.IMAGE_REPO_localhost_5001_saga_fulfillment_rs}}"
          applications.sagas[1].image.tag: "{{.IMAGE_TAG_localhost_5001_saga_fulfillment_rs}}"
          applications.sagas[2].image.repository: "{{.IMAGE_REPO_localhost_5001_saga_cancellation_rs}}"
          applications.sagas[2].image.tag: "{{.IMAGE_TAG_localhost_5001_saga_cancellation_rs}}"

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local:
        push: true
