apiVersion: v1
kind: Service
metadata:
  name: {{ include "angzarr-db-immudb.fullname" . }}
  labels:
    {{- include "angzarr-db-immudb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.webPort }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "angzarr-db-immudb.selectorLabels" . | nindent 4 }}
