// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: examples/ai_sidecar.proto

package examples

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Game state
	ModelId     string       `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // Which model to use
	GameVariant GameVariant  `protobuf:"varint,2,opt,name=game_variant,json=gameVariant,proto3,enum=examples.GameVariant" json:"game_variant,omitempty"`
	Phase       BettingPhase `protobuf:"varint,3,opt,name=phase,proto3,enum=examples.BettingPhase" json:"phase,omitempty"`
	// Cards
	HoleCards      []*Card `protobuf:"bytes,4,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`
	CommunityCards []*Card `protobuf:"bytes,5,rep,name=community_cards,json=communityCards,proto3" json:"community_cards,omitempty"`
	// Betting context
	PotSize      int64 `protobuf:"varint,6,opt,name=pot_size,json=potSize,proto3" json:"pot_size,omitempty"`
	StackSize    int64 `protobuf:"varint,7,opt,name=stack_size,json=stackSize,proto3" json:"stack_size,omitempty"`
	AmountToCall int64 `protobuf:"varint,8,opt,name=amount_to_call,json=amountToCall,proto3" json:"amount_to_call,omitempty"`
	MinRaise     int64 `protobuf:"varint,9,opt,name=min_raise,json=minRaise,proto3" json:"min_raise,omitempty"`
	MaxRaise     int64 `protobuf:"varint,10,opt,name=max_raise,json=maxRaise,proto3" json:"max_raise,omitempty"`
	// Position info
	Position         int32 `protobuf:"varint,11,opt,name=position,proto3" json:"position,omitempty"` // 0 = button, increasing = earlier
	PlayersRemaining int32 `protobuf:"varint,12,opt,name=players_remaining,json=playersRemaining,proto3" json:"players_remaining,omitempty"`
	PlayersToAct     int32 `protobuf:"varint,13,opt,name=players_to_act,json=playersToAct,proto3" json:"players_to_act,omitempty"`
	// Historical context (for recurrent models)
	ActionHistory []*ActionHistory `protobuf:"bytes,14,rep,name=action_history,json=actionHistory,proto3" json:"action_history,omitempty"`
	// Opponent modeling (optional)
	Opponents     []*OpponentStats `protobuf:"bytes,15,rep,name=opponents,proto3" json:"opponents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_examples_ai_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_ai_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_examples_ai_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *ActionRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ActionRequest) GetGameVariant() GameVariant {
	if x != nil {
		return x.GameVariant
	}
	return GameVariant_GAME_VARIANT_UNSPECIFIED
}

func (x *ActionRequest) GetPhase() BettingPhase {
	if x != nil {
		return x.Phase
	}
	return BettingPhase_BETTING_PHASE_UNSPECIFIED
}

func (x *ActionRequest) GetHoleCards() []*Card {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

func (x *ActionRequest) GetCommunityCards() []*Card {
	if x != nil {
		return x.CommunityCards
	}
	return nil
}

func (x *ActionRequest) GetPotSize() int64 {
	if x != nil {
		return x.PotSize
	}
	return 0
}

func (x *ActionRequest) GetStackSize() int64 {
	if x != nil {
		return x.StackSize
	}
	return 0
}

func (x *ActionRequest) GetAmountToCall() int64 {
	if x != nil {
		return x.AmountToCall
	}
	return 0
}

func (x *ActionRequest) GetMinRaise() int64 {
	if x != nil {
		return x.MinRaise
	}
	return 0
}

func (x *ActionRequest) GetMaxRaise() int64 {
	if x != nil {
		return x.MaxRaise
	}
	return 0
}

func (x *ActionRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ActionRequest) GetPlayersRemaining() int32 {
	if x != nil {
		return x.PlayersRemaining
	}
	return 0
}

func (x *ActionRequest) GetPlayersToAct() int32 {
	if x != nil {
		return x.PlayersToAct
	}
	return 0
}

func (x *ActionRequest) GetActionHistory() []*ActionHistory {
	if x != nil {
		return x.ActionHistory
	}
	return nil
}

func (x *ActionRequest) GetOpponents() []*OpponentStats {
	if x != nil {
		return x.Opponents
	}
	return nil
}

type ActionHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerRoot    []byte                 `protobuf:"bytes,1,opt,name=player_root,json=playerRoot,proto3" json:"player_root,omitempty"`
	Action        ActionType             `protobuf:"varint,2,opt,name=action,proto3,enum=examples.ActionType" json:"action,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Phase         BettingPhase           `protobuf:"varint,4,opt,name=phase,proto3,enum=examples.BettingPhase" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionHistory) Reset() {
	*x = ActionHistory{}
	mi := &file_examples_ai_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionHistory) ProtoMessage() {}

func (x *ActionHistory) ProtoReflect() protoreflect.Message {
	mi := &file_examples_ai_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionHistory.ProtoReflect.Descriptor instead.
func (*ActionHistory) Descriptor() ([]byte, []int) {
	return file_examples_ai_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *ActionHistory) GetPlayerRoot() []byte {
	if x != nil {
		return x.PlayerRoot
	}
	return nil
}

func (x *ActionHistory) GetAction() ActionType {
	if x != nil {
		return x.Action
	}
	return ActionType_ACTION_UNSPECIFIED
}

func (x *ActionHistory) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ActionHistory) GetPhase() BettingPhase {
	if x != nil {
		return x.Phase
	}
	return BettingPhase_BETTING_PHASE_UNSPECIFIED
}

type OpponentStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerRoot    []byte                 `protobuf:"bytes,1,opt,name=player_root,json=playerRoot,proto3" json:"player_root,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Stack         int64                  `protobuf:"varint,3,opt,name=stack,proto3" json:"stack,omitempty"`
	Vpip          float32                `protobuf:"fixed32,4,opt,name=vpip,proto3" json:"vpip,omitempty"`             // Voluntarily put in pot %
	Pfr           float32                `protobuf:"fixed32,5,opt,name=pfr,proto3" json:"pfr,omitempty"`               // Pre-flop raise %
	Aggression    float32                `protobuf:"fixed32,6,opt,name=aggression,proto3" json:"aggression,omitempty"` // Bet/raise frequency
	HandsPlayed   int32                  `protobuf:"varint,7,opt,name=hands_played,json=handsPlayed,proto3" json:"hands_played,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpponentStats) Reset() {
	*x = OpponentStats{}
	mi := &file_examples_ai_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpponentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpponentStats) ProtoMessage() {}

func (x *OpponentStats) ProtoReflect() protoreflect.Message {
	mi := &file_examples_ai_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpponentStats.ProtoReflect.Descriptor instead.
func (*OpponentStats) Descriptor() ([]byte, []int) {
	return file_examples_ai_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *OpponentStats) GetPlayerRoot() []byte {
	if x != nil {
		return x.PlayerRoot
	}
	return nil
}

func (x *OpponentStats) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *OpponentStats) GetStack() int64 {
	if x != nil {
		return x.Stack
	}
	return 0
}

func (x *OpponentStats) GetVpip() float32 {
	if x != nil {
		return x.Vpip
	}
	return 0
}

func (x *OpponentStats) GetPfr() float32 {
	if x != nil {
		return x.Pfr
	}
	return 0
}

func (x *OpponentStats) GetAggression() float32 {
	if x != nil {
		return x.Aggression
	}
	return 0
}

func (x *OpponentStats) GetHandsPlayed() int32 {
	if x != nil {
		return x.HandsPlayed
	}
	return 0
}

type ActionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RecommendedAction ActionType             `protobuf:"varint,1,opt,name=recommended_action,json=recommendedAction,proto3,enum=examples.ActionType" json:"recommended_action,omitempty"`
	Amount            int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // For bet/raise
	// Confidence scores for each action (for analysis)
	FoldProbability      float32 `protobuf:"fixed32,3,opt,name=fold_probability,json=foldProbability,proto3" json:"fold_probability,omitempty"`
	CheckCallProbability float32 `protobuf:"fixed32,4,opt,name=check_call_probability,json=checkCallProbability,proto3" json:"check_call_probability,omitempty"`
	BetRaiseProbability  float32 `protobuf:"fixed32,5,opt,name=bet_raise_probability,json=betRaiseProbability,proto3" json:"bet_raise_probability,omitempty"`
	// Model metadata
	ModelVersion    string `protobuf:"bytes,6,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	InferenceTimeMs int64  `protobuf:"varint,7,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_examples_ai_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_ai_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_examples_ai_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *ActionResponse) GetRecommendedAction() ActionType {
	if x != nil {
		return x.RecommendedAction
	}
	return ActionType_ACTION_UNSPECIFIED
}

func (x *ActionResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ActionResponse) GetFoldProbability() float32 {
	if x != nil {
		return x.FoldProbability
	}
	return 0
}

func (x *ActionResponse) GetCheckCallProbability() float32 {
	if x != nil {
		return x.CheckCallProbability
	}
	return 0
}

func (x *ActionResponse) GetBetRaiseProbability() float32 {
	if x != nil {
		return x.BetRaiseProbability
	}
	return 0
}

func (x *ActionResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ActionResponse) GetInferenceTimeMs() int64 {
	if x != nil {
		return x.InferenceTimeMs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_examples_ai_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_ai_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_examples_ai_sidecar_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ModelId        string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelVersion   string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	RequestsServed int64                  `protobuf:"varint,5,opt,name=requests_served,json=requestsServed,proto3" json:"requests_served,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_examples_ai_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_ai_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_examples_ai_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *HealthResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetRequestsServed() int64 {
	if x != nil {
		return x.RequestsServed
	}
	return 0
}

type BatchActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ActionRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchActionRequest) Reset() {
	*x = BatchActionRequest{}
	mi := &file_examples_ai_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchActionRequest) ProtoMessage() {}

func (x *BatchActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_ai_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchActionRequest.ProtoReflect.Descriptor instead.
func (*BatchActionRequest) Descriptor() ([]byte, []int) {
	return file_examples_ai_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *BatchActionRequest) GetRequests() []*ActionRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*ActionResponse      `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchActionResponse) Reset() {
	*x = BatchActionResponse{}
	mi := &file_examples_ai_sidecar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchActionResponse) ProtoMessage() {}

func (x *BatchActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_ai_sidecar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchActionResponse.ProtoReflect.Descriptor instead.
func (*BatchActionResponse) Descriptor() ([]byte, []int) {
	return file_examples_ai_sidecar_proto_rawDescGZIP(), []int{7}
}

func (x *BatchActionResponse) GetResponses() []*ActionResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_examples_ai_sidecar_proto protoreflect.FileDescriptor

const file_examples_ai_sidecar_proto_rawDesc = "" +
	"\n" +
	"\x19examples/ai_sidecar.proto\x12\bexamples\x1a\x1aexamples/poker_types.proto\"\xfa\x04\n" +
	"\rActionRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x128\n" +
	"\fgame_variant\x18\x02 \x01(\x0e2\x15.examples.GameVariantR\vgameVariant\x12,\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x16.examples.BettingPhaseR\x05phase\x12-\n" +
	"\n" +
	"hole_cards\x18\x04 \x03(\v2\x0e.examples.CardR\tholeCards\x127\n" +
	"\x0fcommunity_cards\x18\x05 \x03(\v2\x0e.examples.CardR\x0ecommunityCards\x12\x19\n" +
	"\bpot_size\x18\x06 \x01(\x03R\apotSize\x12\x1d\n" +
	"\n" +
	"stack_size\x18\a \x01(\x03R\tstackSize\x12$\n" +
	"\x0eamount_to_call\x18\b \x01(\x03R\famountToCall\x12\x1b\n" +
	"\tmin_raise\x18\t \x01(\x03R\bminRaise\x12\x1b\n" +
	"\tmax_raise\x18\n" +
	" \x01(\x03R\bmaxRaise\x12\x1a\n" +
	"\bposition\x18\v \x01(\x05R\bposition\x12+\n" +
	"\x11players_remaining\x18\f \x01(\x05R\x10playersRemaining\x12$\n" +
	"\x0eplayers_to_act\x18\r \x01(\x05R\fplayersToAct\x12>\n" +
	"\x0eaction_history\x18\x0e \x03(\v2\x17.examples.ActionHistoryR\ractionHistory\x125\n" +
	"\topponents\x18\x0f \x03(\v2\x17.examples.OpponentStatsR\topponents\"\xa4\x01\n" +
	"\rActionHistory\x12\x1f\n" +
	"\vplayer_root\x18\x01 \x01(\fR\n" +
	"playerRoot\x12,\n" +
	"\x06action\x18\x02 \x01(\x0e2\x14.examples.ActionTypeR\x06action\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12,\n" +
	"\x05phase\x18\x04 \x01(\x0e2\x16.examples.BettingPhaseR\x05phase\"\xcb\x01\n" +
	"\rOpponentStats\x12\x1f\n" +
	"\vplayer_root\x18\x01 \x01(\fR\n" +
	"playerRoot\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12\x14\n" +
	"\x05stack\x18\x03 \x01(\x03R\x05stack\x12\x12\n" +
	"\x04vpip\x18\x04 \x01(\x02R\x04vpip\x12\x10\n" +
	"\x03pfr\x18\x05 \x01(\x02R\x03pfr\x12\x1e\n" +
	"\n" +
	"aggression\x18\x06 \x01(\x02R\n" +
	"aggression\x12!\n" +
	"\fhands_played\x18\a \x01(\x05R\vhandsPlayed\"\xd3\x02\n" +
	"\x0eActionResponse\x12C\n" +
	"\x12recommended_action\x18\x01 \x01(\x0e2\x14.examples.ActionTypeR\x11recommendedAction\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12)\n" +
	"\x10fold_probability\x18\x03 \x01(\x02R\x0ffoldProbability\x124\n" +
	"\x16check_call_probability\x18\x04 \x01(\x02R\x14checkCallProbability\x122\n" +
	"\x15bet_raise_probability\x18\x05 \x01(\x02R\x13betRaiseProbability\x12#\n" +
	"\rmodel_version\x18\x06 \x01(\tR\fmodelVersion\x12*\n" +
	"\x11inference_time_ms\x18\a \x01(\x03R\x0finferenceTimeMs\"\x0f\n" +
	"\rHealthRequest\"\xba\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0frequests_served\x18\x05 \x01(\x03R\x0erequestsServed\"I\n" +
	"\x12BatchActionRequest\x123\n" +
	"\brequests\x18\x01 \x03(\v2\x17.examples.ActionRequestR\brequests\"M\n" +
	"\x13BatchActionResponse\x126\n" +
	"\tresponses\x18\x01 \x03(\v2\x18.examples.ActionResponseR\tresponses2\xd8\x01\n" +
	"\tAiSidecar\x12>\n" +
	"\tGetAction\x12\x17.examples.ActionRequest\x1a\x18.examples.ActionResponse\x12;\n" +
	"\x06Health\x12\x17.examples.HealthRequest\x1a\x18.examples.HealthResponse\x12N\n" +
	"\x0fGetActionsBatch\x12\x1c.examples.BatchActionRequest\x1a\x1d.examples.BatchActionResponseB\x9a\x01\n" +
	"\fcom.examplesB\x0eAiSidecarProtoP\x01Z:github.com/benjaminabbitt/angzarr/client/go/proto/examples\xa2\x02\x03EXX\xaa\x02\bExamples\xca\x02\bExamples\xe2\x02\x14Examples\\GPBMetadata\xea\x02\bExamplesb\x06proto3"

var (
	file_examples_ai_sidecar_proto_rawDescOnce sync.Once
	file_examples_ai_sidecar_proto_rawDescData []byte
)

func file_examples_ai_sidecar_proto_rawDescGZIP() []byte {
	file_examples_ai_sidecar_proto_rawDescOnce.Do(func() {
		file_examples_ai_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_ai_sidecar_proto_rawDesc), len(file_examples_ai_sidecar_proto_rawDesc)))
	})
	return file_examples_ai_sidecar_proto_rawDescData
}

var file_examples_ai_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_examples_ai_sidecar_proto_goTypes = []any{
	(*ActionRequest)(nil),       // 0: examples.ActionRequest
	(*ActionHistory)(nil),       // 1: examples.ActionHistory
	(*OpponentStats)(nil),       // 2: examples.OpponentStats
	(*ActionResponse)(nil),      // 3: examples.ActionResponse
	(*HealthRequest)(nil),       // 4: examples.HealthRequest
	(*HealthResponse)(nil),      // 5: examples.HealthResponse
	(*BatchActionRequest)(nil),  // 6: examples.BatchActionRequest
	(*BatchActionResponse)(nil), // 7: examples.BatchActionResponse
	(GameVariant)(0),            // 8: examples.GameVariant
	(BettingPhase)(0),           // 9: examples.BettingPhase
	(*Card)(nil),                // 10: examples.Card
	(ActionType)(0),             // 11: examples.ActionType
}
var file_examples_ai_sidecar_proto_depIdxs = []int32{
	8,  // 0: examples.ActionRequest.game_variant:type_name -> examples.GameVariant
	9,  // 1: examples.ActionRequest.phase:type_name -> examples.BettingPhase
	10, // 2: examples.ActionRequest.hole_cards:type_name -> examples.Card
	10, // 3: examples.ActionRequest.community_cards:type_name -> examples.Card
	1,  // 4: examples.ActionRequest.action_history:type_name -> examples.ActionHistory
	2,  // 5: examples.ActionRequest.opponents:type_name -> examples.OpponentStats
	11, // 6: examples.ActionHistory.action:type_name -> examples.ActionType
	9,  // 7: examples.ActionHistory.phase:type_name -> examples.BettingPhase
	11, // 8: examples.ActionResponse.recommended_action:type_name -> examples.ActionType
	0,  // 9: examples.BatchActionRequest.requests:type_name -> examples.ActionRequest
	3,  // 10: examples.BatchActionResponse.responses:type_name -> examples.ActionResponse
	0,  // 11: examples.AiSidecar.GetAction:input_type -> examples.ActionRequest
	4,  // 12: examples.AiSidecar.Health:input_type -> examples.HealthRequest
	6,  // 13: examples.AiSidecar.GetActionsBatch:input_type -> examples.BatchActionRequest
	3,  // 14: examples.AiSidecar.GetAction:output_type -> examples.ActionResponse
	5,  // 15: examples.AiSidecar.Health:output_type -> examples.HealthResponse
	7,  // 16: examples.AiSidecar.GetActionsBatch:output_type -> examples.BatchActionResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_examples_ai_sidecar_proto_init() }
func file_examples_ai_sidecar_proto_init() {
	if File_examples_ai_sidecar_proto != nil {
		return
	}
	file_examples_poker_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_ai_sidecar_proto_rawDesc), len(file_examples_ai_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_ai_sidecar_proto_goTypes,
		DependencyIndexes: file_examples_ai_sidecar_proto_depIdxs,
		MessageInfos:      file_examples_ai_sidecar_proto_msgTypes,
	}.Build()
	File_examples_ai_sidecar_proto = out.File
	file_examples_ai_sidecar_proto_goTypes = nil
	file_examples_ai_sidecar_proto_depIdxs = nil
}
