// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: examples/projections.proto

package examples

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Receipt projection generated when an order completes
type Receipt struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrderId             string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId          string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Items               []*LineItem            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	SubtotalCents       int32                  `protobuf:"varint,4,opt,name=subtotal_cents,json=subtotalCents,proto3" json:"subtotal_cents,omitempty"`
	DiscountCents       int32                  `protobuf:"varint,5,opt,name=discount_cents,json=discountCents,proto3" json:"discount_cents,omitempty"`
	FinalTotalCents     int32                  `protobuf:"varint,6,opt,name=final_total_cents,json=finalTotalCents,proto3" json:"final_total_cents,omitempty"`
	PaymentMethod       string                 `protobuf:"bytes,7,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	LoyaltyPointsEarned int32                  `protobuf:"varint,8,opt,name=loyalty_points_earned,json=loyaltyPointsEarned,proto3" json:"loyalty_points_earned,omitempty"`
	CompletedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	FormattedText       string                 `protobuf:"bytes,10,opt,name=formatted_text,json=formattedText,proto3" json:"formatted_text,omitempty"` // Human-readable receipt text
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_examples_projections_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_examples_projections_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_examples_projections_proto_rawDescGZIP(), []int{0}
}

func (x *Receipt) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Receipt) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Receipt) GetItems() []*LineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Receipt) GetSubtotalCents() int32 {
	if x != nil {
		return x.SubtotalCents
	}
	return 0
}

func (x *Receipt) GetDiscountCents() int32 {
	if x != nil {
		return x.DiscountCents
	}
	return 0
}

func (x *Receipt) GetFinalTotalCents() int32 {
	if x != nil {
		return x.FinalTotalCents
	}
	return 0
}

func (x *Receipt) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Receipt) GetLoyaltyPointsEarned() int32 {
	if x != nil {
		return x.LoyaltyPointsEarned
	}
	return 0
}

func (x *Receipt) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Receipt) GetFormattedText() string {
	if x != nil {
		return x.FormattedText
	}
	return ""
}

var File_examples_projections_proto protoreflect.FileDescriptor

const file_examples_projections_proto_rawDesc = "" +
	"\n" +
	"\x1aexamples/projections.proto\x12\bexamples\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14examples/order.proto\"\xaa\x03\n" +
	"\aReceipt\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12(\n" +
	"\x05items\x18\x03 \x03(\v2\x12.examples.LineItemR\x05items\x12%\n" +
	"\x0esubtotal_cents\x18\x04 \x01(\x05R\rsubtotalCents\x12%\n" +
	"\x0ediscount_cents\x18\x05 \x01(\x05R\rdiscountCents\x12*\n" +
	"\x11final_total_cents\x18\x06 \x01(\x05R\x0ffinalTotalCents\x12%\n" +
	"\x0epayment_method\x18\a \x01(\tR\rpaymentMethod\x122\n" +
	"\x15loyalty_points_earned\x18\b \x01(\x05R\x13loyaltyPointsEarned\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12%\n" +
	"\x0eformatted_text\x18\n" +
	" \x01(\tR\rformattedTextB\x9c\x01\n" +
	"\fcom.examplesB\x10ProjectionsProtoP\x01Z:github.com/benjaminabbitt/angzarr/client/go/proto/examples\xa2\x02\x03EXX\xaa\x02\bExamples\xca\x02\bExamples\xe2\x02\x14Examples\\GPBMetadata\xea\x02\bExamplesb\x06proto3"

var (
	file_examples_projections_proto_rawDescOnce sync.Once
	file_examples_projections_proto_rawDescData []byte
)

func file_examples_projections_proto_rawDescGZIP() []byte {
	file_examples_projections_proto_rawDescOnce.Do(func() {
		file_examples_projections_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_projections_proto_rawDesc), len(file_examples_projections_proto_rawDesc)))
	})
	return file_examples_projections_proto_rawDescData
}

var file_examples_projections_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_projections_proto_goTypes = []any{
	(*Receipt)(nil),               // 0: examples.Receipt
	(*LineItem)(nil),              // 1: examples.LineItem
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_examples_projections_proto_depIdxs = []int32{
	1, // 0: examples.Receipt.items:type_name -> examples.LineItem
	2, // 1: examples.Receipt.completed_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_examples_projections_proto_init() }
func file_examples_projections_proto_init() {
	if File_examples_projections_proto != nil {
		return
	}
	file_examples_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_projections_proto_rawDesc), len(file_examples_projections_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_projections_proto_goTypes,
		DependencyIndexes: file_examples_projections_proto_depIdxs,
		MessageInfos:      file_examples_projections_proto_msgTypes,
	}.Build()
	File_examples_projections_proto = out.File
	file_examples_projections_proto_goTypes = nil
	file_examples_projections_proto_depIdxs = nil
}
