# Business Logic - C#

set shell := ["bash", "-c"]

TOP := `git rev-parse --show-toplevel`

default:
    @just --list

build:
    dotnet build

run:
    dotnet run

clean:
    dotnet clean
    rm -rf bin obj

copy-features:
    rm -rf features
    cp -r {{TOP}}/examples/features .

unit:
    dotnet test --filter "Category!=Acceptance"

acceptance: copy-features
    ANGZARR_TEST_MODE=container dotnet test --filter "Category=Acceptance"

test: unit acceptance

test-unit: unit
